from enum import Enum

# Physical Globals

MIN = -10
MAX = 10

SKIN = [
    "Sunset",
    "Dusk",
    "Sunheat",
    "Olive Skin",
    "Beach",
    "Sunkissed",
    "Rose Kiss",
    "Warmth",
    "Light Rose",
    "Pale Dust",
    "Skin 1",
    "Skin 2",
    "Skin 3",
    "Skin 4",
]
EYE_COLOURS = [
    "Orange",
    "Honey",
    "Red",
    "Hot Pink",
    "Amethyst",
    "Purple",
    "Lilac",
    "Silver",
    "Black",
    "Frost",
    "Ocean",
    "Aqua",
    "Dark Aqua",
    "Light Green",
    "Forest",
    "Light Hazel",
    "Hazel",
    "Dark Hazel",
    "Light Brown",
    "Chocolate",
    "Latte Brown",
    "Almond",
    "Dark Brown",
    "Brown",
    "Light Blue",
    "Dark Blue",
    "Grey",
    "Green",
]
HAIR_COLOUR = ["Black", "Brown", "Blonde", "Red"]
EYEBROWS = [
    "Wow",
    "Wolfman",
    "Vamp",
    "Upswept",
    "Stunner",
    "Sprite",
    "Spaniel",
    "Soft",
    "Smol",
    "Pan",
    "Nyx",
    "ModernArt",
    "Mild",
    "MelonBall",
    "Madame",
    "HWStarletV2",
    "HWStarlet",
    "Hunter",
    "Howl",
    "Hestia",
    "Grizzly",
    "Gnome",
    "GloUp",
    "Ghoul",
    "Gentle",
    "FairyQueen",
    "Dewdrop",
    "Dracula",
    "BushBabyBrow4",
    "BushBabyBrow3",
    "BushBabyBrow2",
    "BushBabyBrow1",
    "BrownN5",
    "BrowN4",
    "BrowN3",
    "BrowN1",
    "Boo",
    "N52",
    "N50",
    "N51",
    "N49",
    "N45",
    "N40",
    "N62",
    "N48",
    "N42",
    "N55",
    "N44",
    "N53",
    "N47",
]
TURN_ONS_OFFS = [
    "Adventurous",
    "Alien",
    "Animal Lover",
    "Artistic",
    "Athletic",
    "Black Hair",
    "Blonde Hair",
    "Brown Hair",
    "Business Shark",
    "Charismatic",
    "Cultured",
    "Expressive",
    "Facial Hair",
    "Fatness",
    "Fitness",
    "Foodie",
    "Grey Hair",
    "Indoorsy",
    "Infamous",
    "Intellect",
    "Introvert",
    "Laid Back",
    "Musical",
    "Occult",
    "Outdoorsy",
    "Outgoing",
    "Plant Lover",
    "Rebellious",
    "Red Hair",
    "Stylish",
    "Technology",
    "Tidy",
    "Undead",
    "Well-Liked",
]
BOOL_ANSWER = [True, False]
FAVOURITE_COLOURS = [
    "Black",
    "Blue",
    "Brown",
    "Green",
    "Grey",
    "Orange",
    "Pink",
    "Purple",
    "Red",
    "Turquoise",
    "White",
    "Yellow",
]

# Mental Globals

# Number of Traits
TODDLER_NUM_TRAITS = 2
CHILD_NUM_TRAITS = 3
TEEN_NUM_TRAITS = 4
ADULT_NUM_TRAITS = 5

# Traits
TODDLER_TRAITS = {
    "absent-minded": 0,
    "artistic": 0,
    "athletic": 0,
    "brave": 0,
    "clumsy": 0,
    "couch potato": 0,
    "disciplined": 0,
    "easily impressed": 0,
    "eccentric": 0,
    "evil": 0,
    "excitable": 0,
    "friendly": 0,
    "genius": 0,
    "good": 0,
    "grumpy": 0,
    "hates the outdoors": 0,
    "heavy sleeper": 0,
    "insane": 0,
    "light sleeper": 0,
    "loner": 0,
    "loves the outdoors": 0,
    "neurotic": 0,
    "perceptive": 0,
    "slob": 0,
    "virtuoso": 0,
}

CHILD_TRAITS = {
    "absent-minded": 0,
    "adventurous": 0,
    "ambitious": 0,
    "angler": 0,
    "artistic": 0,
    "athletic": 0,
    "bookworm": 0,
    "brave": 0,
    "can't stand art": 0,
    "clumsy": 0,
    "computer whiz": 0,
    "couch potato": 0,
    "coward": 0,
    "daredevil": 0,
    "disciplined": 0,
    "easily impressed": 0,
    "eccentric": 0,
    "eco-friendly": 0,
    "evil": 0,
    "excitable": 0,
    "family-oriented": 0,
    "friendly": 0,
    "frugal": 0,
    "genius": 0,
    "good": 0,
    "good sense of humour": 0,
    "grumpy": 0,
    "hates the outdoors": 0,
    "heavy sleeper": 0,
    "hot-headed": 0,
    "hydrophobic": 0,
    "inappropriate": 0,
    "insane": 0,
    "kleptomaniac": 0,
    "light sleeper": 0,
    "loner": 0,
    "loser": 0,
    "loves the outdoors": 0,
    "lucky": 0,
    "mean-spirited": 0,
    "mooch": 0,
    "neat": 0,
    "neurotic": 0,
    "never nude": 0,
    "no sense of humour": 0,
    "over-emotional": 0,
    "party animal": 0,
    "perceptive": 0,
    "perfectionist": 0,
    "photographer's eye": 0,
    "rebellious": 0,
    "shy": 0,
    "slob": 0,
    "snob": 0,
    "star quality": 0,
    "technophobe": 0,
    "unlucky": 0,
    "vegetarian": 0,
    "vehicle enthusiast": 0,
    "virtuoso": 0,
    "workaholic": 0,
}

TEEN_TRAITS = {
    "absent-minded": 0,
    "adventurous": 0,
    "ambitious": 0,
    "angler": 0,
    "artistic": 0,
    "athletic": 0,
    "bookworm": 0,
    "born salesman": 0,
    "brave": 0,
    "can't stand art": 0,
    "charismatic": 0,
    "childish": 0,
    "clumsy": 0,
    "commitment issues": 0,
    "computer whiz": 0,
    "couch potato": 0,
    "coward": 0,
    "daredevil": 0,
    "disciplined": 0,
    "dislikes children": 0,
    "dramatic": 0,
    "easily impressed": 0,
    "eccentric": 0,
    "eco-friendly": 0,
    "evil": 0,
    "excitable": 0,
    "family-oriented": 0,
    "flirty": 0,
    "friendly": 0,
    "frugal": 0,
    "genius": 0,
    "good": 0,
    "good sense of humour": 0,
    "great kisser": 0,
    "green thumb": 0,
    "grumpy": 0,
    "handy": 0,
    "hates the outdoors": 0,
    "heavy sleeper": 0,
    "hopeless romantic": 0,
    "hot-headed": 0,
    "hydrophobic": 0,
    "inappropriate": 0,
    "insane": 0,
    "kleptomaniac": 0,
    "light sleeper": 0,
    "loner": 0,
    "loser": 0,
    "loves the outdoors": 0,
    "lucky": 0,
    "mean-spirited": 0,
    "mooch": 0,
    "natural cook": 0,
    "neat": 0,
    "neurotic": 0,
    "never nude": 0,
    "no sense of humour": 0,
    "nurturing": 0,
    "over-emotional": 0,
    "party animal": 0,
    "perceptive": 0,
    "perfectionist": 0,
    "photographer's eye": 0,
    "rebellious": 0,
    "savvy sculptor": 0,
    "schmoozer": 0,
    "shy": 0,
    "slob": 0,
    "snob": 0,
    "star quality": 0,
    "technophobe": 0,
    "unflirty": 0,
    "unlucky": 0,
    "vegetarian": 0,
    "vehicle enthusiast": 0,
    "virtuoso": 0,
    "workaholic": 0,
}

ADULT_TRAITS = {
    "absent-minded": 0,
    "adventurous": 0,
    "ambitious": 0,
    "angler": 0,
    "animal lover": 0,
    "artistic": 0,
    "athletic": 0,
    "avant garde": 0,
    "bookworm": 0,
    "born salesman": 0,
    "bot fan": 0,
    "brave": 0,
    "brooding": 0,
    "can't stand art": 0,
    "cat person": 0,
    "charismatic": 0,
    "childish": 0,
    "clumsy": 0,
    "commitment issues": 0,
    "computer whiz": 0,
    "couch potato": 0,
    "coward": 0,
    "daredevil": 0,
    "disciplined": 0,
    "dislikes children": 0,
    "diva": 0,
    "dog person": 0,
    "dramatic": 0,
    "easily impressed": 0,
    "eccentric": 0,
    "eco-friendly": 0,
    "equestrian": 0,
    "evil": 0,
    "excitable": 0,
    "family-oriented": 0,
    "flirty": 0,
    "friendly": 0,
    "frugal": 0,
    "gatherer": 0,
    "genius": 0,
    "good": 0,
    "good sense of humour": 0,
    "great kisser": 0,
    "green thumb": 0,
    "grumpy": 0,
    "handy": 0,
    "hates the outdoors": 0,
    "heavy sleeper": 0,
    "hopeless romantic": 0,
    "hot-headed": 0,
    "hydrophobic": 0,
    "inappropriate": 0,
    "insane": 0,
    "irresistible": 0,
    "kleptomaniac": 0,
    "light sleeper": 0,
    "loner": 0,
    "loser": 0,
    "loves the cold": 0,
    "loves the heat": 0,
    "loves the outdoors": 0,
    "loves to swim": 0,
    "lucky": 0,
    "mean-spirited": 0,
    "mooch": 0,
    "natural born performer": 0,
    "natural cook": 0,
    "neat": 0,
    "neurotic": 0,
    "never nude": 0,
    "night owl": 0,
    "no sense of humour": 0,
    "nurturing": 0,
    "over-emotional": 0,
    "party animal": 0,
    "perceptive": 0,
    "perfectionist": 0,
    "photographer's eye": 0,
    "proper": 0,
    "rebellious": 0,
    "sailor": 0,
    "savvy sculptor": 0,
    "schmoozer": 0,
    "shy": 0,
    "slob": 0,
    "snob": 0,
    "social butterfly": 0,
    "socially awkward": 0,
    "star quality": 0,
    "supernatural fan": 0,
    "supernatural sceptic": 0,
    "technophobe": 0,
    "unflirty": 0,
    "unlucky": 0,
    "unstable": 0,
    "vegetarian": 0,
    "vehicle enthusiast": 0,
    "virtuoso": 0,
    "workaholic": 0,
}


# Aspirations
class Aspirations(Enum):
    FAMILY = 1, "Family"
    FORTUNE = 2, "Fortune"
    KNOWLEDGE = 3, "Knowledge"
    PLEASURE = 4, "Pleasure"
    POPULARITY = 5, "Popularity"
    ROMANCE = 6, "Romance"


ASPIRATION_MODEL = {
    "Family": 0,
    "Fortune": 0,
    "Knowledge": 0,
    "Pleasure": 0,
    "Popularity": 0,
    "Romance": 0,
}


# Hobbies
HOBBIES = [
    "Arts & Crafts",
    "Cuisine",
    "Film & Literature",
    "Fitness",
    "Games",
    "Music & Dance",
    "Nature",
    "Science",
    "Sports",
    "Tinkering",
    "Unknown",
]


# Turn Ons/Off
TURN_ONS_OFF = [
    "Adventurous",
    "Alien",
    "Animal Lover",
    "Artistic",
    "Athletic",
    "Black Hair",
    "Blonde Hair",
    "Brown Hair",
    "Business Shark",
    "Charismatic",
    "Cultured",
    "Expressive",
    "Facial Hair",
    "Fatness",
    "Fitness",
    "Foodie",
    "Grey Hair",
    "Indoorsy",
    "Infamous",
    "Intellect",
    "Introvert",
    "Laid Back",
    "Musical",
    "Occult",
    "Outdoorsy",
    "Outgoing",
    "Plant Lover",
    "Rebellious",
    "Red Hair",
    "Stylish",
    "Technology",
    "Tidy",
    "Undead",
    "Well-Liked",
]
