from enum import Enum

# Physical Globals

MIN = -10
MAX = 10

SKIN = [
    "Sunset",
    "Dusk",
    "Sunheat",
    "Olive Skin",
    "Beach",
    "Sunkissed",
    "Rose Kiss",
    "Warmth",
    "Light Rose",
    "Pale Dust",
    "Skin 1",
    "Skin 2",
    "Skin 3",
    "Skin 4",
]
EYE_COLOURS = [
    "Orange",
    "Honey",
    "Red",
    "Hot Pink",
    "Amethyst",
    "Purple",
    "Lilac",
    "Silver",
    "Black",
    "Frost",
    "Ocean",
    "Aqua",
    "Dark Aqua",
    "Light Green",
    "Forest",
    "Light Hazel",
    "Hazel",
    "Dark Hazel",
    "Light Brown",
    "Chocolate",
    "Latte Brown",
    "Almond",
    "Dark Brown",
    "Brown",
    "Light Blue",
    "Dark Blue",
    "Grey",
    "Green",
]
HAIR_COLOUR = ["Black", "Brown", "Blonde", "Red"]
EYEBROWS = [
    "Wow",
    "Wolfman",
    "Vamp",
    "Upswept",
    "Stunner",
    "Sprite",
    "Spaniel",
    "Soft",
    "Smol",
    "Pan",
    "Nyx",
    "ModernArt",
    "Mild",
    "MelonBall",
    "Madame",
    "HWStarletV2",
    "HWStarlet",
    "Hunter",
    "Howl",
    "Hestia",
    "Grizzly",
    "Gnome",
    "GloUp",
    "Ghoul",
    "Gentle",
    "FairyQueen",
    "Dewdrop",
    "Dracula",
    "BushBabyBrow4",
    "BushBabyBrow3",
    "BushBabyBrow2",
    "BushBabyBrow1",
    "BrownN5",
    "BrowN4",
    "BrowN3",
    "BrowN1",
    "Boo",
    "N52",
    "N50",
    "N51",
    "N49",
    "N45",
    "N40",
    "N62",
    "N48",
    "N42",
    "N55",
    "N44",
    "N53",
    "N47",
]
TURN_ONS_OFFS = [
    "Adventurous",
    "Alien",
    "Animal Lover",
    "Artistic",
    "Athletic",
    "Black Hair",
    "Blonde Hair",
    "Brown Hair",
    "Business Shark",
    "Charismatic",
    "Cultured",
    "Expressive",
    "Facial Hair",
    "Fatness",
    "Fitness",
    "Foodie",
    "Grey Hair",
    "Indoorsy",
    "Infamous",
    "Intellect",
    "Introvert",
    "Laid Back",
    "Musical",
    "Occult",
    "Outdoorsy",
    "Outgoing",
    "Plant Lover",
    "Rebellious",
    "Red Hair",
    "Stylish",
    "Technology",
    "Tidy",
    "Undead",
    "Well-Liked",
]
BOOL_ANSWER = [True, False]
FAVOURITE_COLOURS = [
    "Black",
    "Blue",
    "Brown",
    "Green",
    "Grey",
    "Orange",
    "Pink",
    "Purple",
    "Red",
    "Turquoise",
    "White",
    "Yellow",
]

# Mental Globals

# Number of Traits
TODDLER_NUM_TRAITS = 2
CHILD_NUM_TRAITS = 3
TEEN_NUM_TRAITS = 4
ADULT_NUM_TRAITS = 5

# Traits
TODDLER_TRAITS = {
    "absent-minded": 0,
    "artistic": 0,
    "athletic": 0,
    "brave": 0,
    "clumsy": 0,
    "couch potato": 0,
    "disciplined": 0,
    "easily impressed": 0,
    "eccentric": 0,
    "evil": 0,
    "excitable": 0,
    "friendly": 0,
    "genius": 0,
    "good": 0,
    "grumpy": 0,
    "hates the outdoors": 0,
    "heavy sleeper": 0,
    "insane": 0,
    "light sleeper": 0,
    "loner": 0,
    "loves the outdoors": 0,
    "neurotic": 0,
    "perceptive": 0,
    "slob": 0,
    "virtuoso": 0,
}

CHILD_TRAITS = {
    "absent-minded": 0,
    "adventurous": 0,
    "ambitious": 0,
    "angler": 0,
    "artistic": 0,
    "athletic": 0,
    "bookworm": 0,
    "brave": 0,
    "can't stand art": 0,
    "clumsy": 0,
    "computer whiz": 0,
    "couch potato": 0,
    "coward": 0,
    "daredevil": 0,
    "disciplined": 0,
    "easily impressed": 0,
    "eccentric": 0,
    "eco-friendly": 0,
    "evil": 0,
    "excitable": 0,
    "family-oriented": 0,
    "friendly": 0,
    "frugal": 0,
    "genius": 0,
    "good": 0,
    "good sense of humour": 0,
    "grumpy": 0,
    "hates the outdoors": 0,
    "heavy sleeper": 0,
    "hot-headed": 0,
    "hydrophobic": 0,
    "inappropriate": 0,
    "insane": 0,
    "kleptomaniac": 0,
    "light sleeper": 0,
    "loner": 0,
    "loser": 0,
    "loves the outdoors": 0,
    "lucky": 0,
    "mean-spirited": 0,
    "mooch": 0,
    "neat": 0,
    "neurotic": 0,
    "never nude": 0,
    "no sense of humour": 0,
    "over-emotional": 0,
    "party animal": 0,
    "perceptive": 0,
    "perfectionist": 0,
    "photographer's eye": 0,
    "rebellious": 0,
    "shy": 0,
    "slob": 0,
    "snob": 0,
    "star quality": 0,
    "technophobe": 0,
    "unlucky": 0,
    "vegetarian": 0,
    "vehicle enthusiast": 0,
    "virtuoso": 0,
    "workaholic": 0,
}

TEEN_TRAITS = {
    "absent-minded": 0,
    "adventurous": 0,
    "ambitious": 0,
    "angler": 0,
    "artistic": 0,
    "athletic": 0,
    "bookworm": 0,
    "born salesman": 0,
    "brave": 0,
    "can't stand art": 0,
    "charismatic": 0,
    "childish": 0,
    "clumsy": 0,
    "commitment issues": 0,
    "computer whiz": 0,
    "couch potato": 0,
    "coward": 0,
    "daredevil": 0,
    "disciplined": 0,
    "dislikes children": 0,
    "dramatic": 0,
    "easily impressed": 0,
    "eccentric": 0,
    "eco-friendly": 0,
    "evil": 0,
    "excitable": 0,
    "family-oriented": 0,
    "flirty": 0,
    "friendly": 0,
    "frugal": 0,
    "genius": 0,
    "good": 0,
    "good sense of humour": 0,
    "great kisser": 0,
    "green thumb": 0,
    "grumpy": 0,
    "handy": 0,
    "hates the outdoors": 0,
    "heavy sleeper": 0,
    "hopeless romantic": 0,
    "hot-headed": 0,
    "hydrophobic": 0,
    "inappropriate": 0,
    "insane": 0,
    "kleptomaniac": 0,
    "light sleeper": 0,
    "loner": 0,
    "loser": 0,
    "loves the outdoors": 0,
    "lucky": 0,
    "mean-spirited": 0,
    "mooch": 0,
    "natural cook": 0,
    "neat": 0,
    "neurotic": 0,
    "never nude": 0,
    "no sense of humour": 0,
    "nurturing": 0,
    "over-emotional": 0,
    "party animal": 0,
    "perceptive": 0,
    "perfectionist": 0,
    "photographer's eye": 0,
    "rebellious": 0,
    "savvy sculptor": 0,
    "schmoozer": 0,
    "shy": 0,
    "slob": 0,
    "snob": 0,
    "star quality": 0,
    "technophobe": 0,
    "unflirty": 0,
    "unlucky": 0,
    "vegetarian": 0,
    "vehicle enthusiast": 0,
    "virtuoso": 0,
    "workaholic": 0,
}

ADULT_TRAITS = {
    "absent-minded": 0,
    "adventurous": 0,
    "ambitious": 0,
    "angler": 0,
    "animal lover": 0,
    "artistic": 0,
    "athletic": 0,
    "avant garde": 0,
    "bookworm": 0,
    "born salesman": 0,
    "bot fan": 0,
    "brave": 0,
    "brooding": 0,
    "can't stand art": 0,
    "cat person": 0,
    "charismatic": 0,
    "childish": 0,
    "clumsy": 0,
    "commitment issues": 0,
    "computer whiz": 0,
    "couch potato": 0,
    "coward": 0,
    "daredevil": 0,
    "disciplined": 0,
    "dislikes children": 0,
    "diva": 0,
    "dog person": 0,
    "dramatic": 0,
    "easily impressed": 0,
    "eccentric": 0,
    "eco-friendly": 0,
    "equestrian": 0,
    "evil": 0,
    "excitable": 0,
    "family-oriented": 0,
    "flirty": 0,
    "friendly": 0,
    "frugal": 0,
    "gatherer": 0,
    "genius": 0,
    "good": 0,
    "good sense of humour": 0,
    "great kisser": 0,
    "green thumb": 0,
    "grumpy": 0,
    "handy": 0,
    "hates the outdoors": 0,
    "heavy sleeper": 0,
    "hopeless romantic": 0,
    "hot-headed": 0,
    "hydrophobic": 0,
    "inappropriate": 0,
    "insane": 0,
    "irresistible": 0,
    "kleptomaniac": 0,
    "light sleeper": 0,
    "loner": 0,
    "loser": 0,
    "loves the cold": 0,
    "loves the heat": 0,
    "loves the outdoors": 0,
    "loves to swim": 0,
    "lucky": 0,
    "mean-spirited": 0,
    "mooch": 0,
    "natural born performer": 0,
    "natural cook": 0,
    "neat": 0,
    "neurotic": 0,
    "never nude": 0,
    "night owl": 0,
    "no sense of humour": 0,
    "nurturing": 0,
    "over-emotional": 0,
    "party animal": 0,
    "perceptive": 0,
    "perfectionist": 0,
    "photographer's eye": 0,
    "proper": 0,
    "rebellious": 0,
    "sailor": 0,
    "savvy sculptor": 0,
    "schmoozer": 0,
    "shy": 0,
    "slob": 0,
    "snob": 0,
    "social butterfly": 0,
    "socially awkward": 0,
    "star quality": 0,
    "supernatural fan": 0,
    "supernatural sceptic": 0,
    "technophobe": 0,
    "unflirty": 0,
    "unlucky": 0,
    "unstable": 0,
    "vegetarian": 0,
    "vehicle enthusiast": 0,
    "virtuoso": 0,
    "workaholic": 0,
}


# Aspirations
class Aspirations(Enum):
    FAMILY = 1, "Family"
    FORTUNE = 2, "Fortune"
    KNOWLEDGE = 3, "Knowledge"
    PLEASURE = 4, "Pleasure"
    POPULARITY = 5, "Popularity"
    ROMANCE = 6, "Romance"


ASPIRATION_MODEL = {
    "Family": 0,
    "Fortune": 0,
    "Knowledge": 0,
    "Pleasure": 0,
    "Popularity": 0,
    "Romance": 0,
}


# Hobbies
HOBBIES = [
    "Arts & Crafts",
    "Cuisine",
    "Film & Literature",
    "Fitness",
    "Games",
    "Music & Dance",
    "Nature",
    "Science",
    "Sports",
    "Tinkering",
    "Unknown",
]


# Turn Ons/Off
TURN_ONS_OFF = [
    "Adventurous",
    "Alien",
    "Animal Lover",
    "Artistic",
    "Athletic",
    "Black Hair",
    "Blonde Hair",
    "Brown Hair",
    "Business Shark",
    "Charismatic",
    "Cultured",
    "Expressive",
    "Facial Hair",
    "Fatness",
    "Fitness",
    "Foodie",
    "Grey Hair",
    "Indoorsy",
    "Infamous",
    "Intellect",
    "Introvert",
    "Laid Back",
    "Musical",
    "Occult",
    "Outdoorsy",
    "Outgoing",
    "Plant Lover",
    "Rebellious",
    "Red Hair",
    "Stylish",
    "Technology",
    "Tidy",
    "Undead",
    "Well-Liked",
]

# Trait Conflicts
TODDLER_CONFLICTS = [
    {"traitName": "perceptive", "conflict1": "absent-minded"},
    {"traitName": "couch potato", "conflict1": "athletic", "conflict3": "disciplined"},
    {"traitName": "athletic", "conflict1": "couch potato"},
    {"traitName": "disciplined", "conflict1": "couch potato"},
    {"traitName": "good", "conflict1": "evil"},
    {
        "traitName": "grumpy",
        "conflict1": "excitable",
    },
    {"traitName": "evil", "conflict1": "good"},
    {
        "traitName": "excitable",
        "conflict1": "grumpy",
    },
    {"traitName": "loves the outdoors", "conflict1": "hates the outdoors"},
    {"traitName": "light sleeper", "conflict1": "heavy sleeper"},
    {"traitName": "heavy sleeper", "conflict1": "light sleeper"},
    {
        "traitName": "hates the outdoors",
        "conflict1": "loves the outdoors",
    },
    {"traitName": "absent-minded", "conflict1": "perceptive"},
]

CHILD_CONFLICTS = [
    {"traitName": "perceptive", "conflict1": "absent-minded"},
    {
        "traitName": "can't stand art",
        "conflict1": "artistic",
        "conflict2": "easily impressed",
    },
    {
        "traitName": "couch potato",
        "conflict1": "athletic",
        "conflict2": "technophobe",
        "conflict3": "disciplined",
    },
    {
        "traitName": "loser",
        "conflict1": "brave",
    },
    {
        "traitName": "coward",
        "conflict1": "brave",
        "conflict2": "daredevil",
    },
    {"traitName": "artistic", "conflict1": "can't stand art"},
    {
        "traitName": "easily impressed",
        "conflict1": "can't stand art",
        "conflict2": "snob",
    },
    {
        "traitName": "technophobe",
        "conflict1": "computer whiz",
        "conflict2": "couch potato",
    },
    {"traitName": "athletic", "conflict1": "couch potato"},
    {"traitName": "disciplined", "conflict1": "couch potato"},
    {"traitName": "daredevil", "conflict1": "coward"},
    {"traitName": "brave", "conflict1": "coward", "conflict2": "loser"},
    {"traitName": "snob", "conflict1": "easily impressed"},
    {"traitName": "good", "conflict1": "evil"},
    {"traitName": "grumpy", "conflict1": "excitable", "conflict2": "hot-headed"},
    {
        "traitName": "shy",
        "conflict2": "party animal",
    },
    {"traitName": "mean-spirited", "conflict1": "friendly"},
    {"traitName": "evil", "conflict1": "good"},
    {"traitName": "no sense of humour", "conflict1": "good sense of humour"},
    {"traitName": "hot-headed", "conflict1": "grumpy"},
    {
        "traitName": "excitable",
        "conflict1": "grumpy",
    },
    {"traitName": "eco-friendly", "conflict1": "hates the outdoors"},
    {"traitName": "loves the outdoors", "conflict1": "hates the outdoors"},
    {"traitName": "light sleeper", "conflict1": "heavy sleeper"},
    {"traitName": "heavy sleeper", "conflict1": "light sleeper"},
    {"traitName": "party animal", "conflict1": "loner", "conflict2": "shy"},
    {
        "traitName": "hates the outdoors",
        "conflict1": "loves the outdoors",
        "conflict2": "eco-friendly",
    },
    {"traitName": "unlucky", "conflict1": "lucky"},
    {"traitName": "friendly", "conflict1": "mean-spirited"},
    {"traitName": "slob", "conflict1": "neat", "conflict2": "proper"},
    {"traitName": "good sense of humour", "conflict1": "no sense of humour"},
    {
        "traitName": "loner",
        "conflict1": "party animal",
    },
    {"traitName": "absent-minded", "conflict1": "perceptive"},
    {"traitName": "neat", "conflict1": "slob"},
    {"traitName": "computer whiz", "conflict1": "technophobe"},
    {"traitName": "lucky", "conflict1": "unlucky"},
]

TEEN_CONFLICTS = [
    {"traitName": "perceptive", "conflict1": "absent-minded"},
    {
        "traitName": "can't stand art",
        "conflict1": "artistic",
        "conflict2": "easily impressed",
        "conflict3": "savvy sculptor",
    },
    {
        "traitName": "couch potato",
        "conflict1": "athletic",
        "conflict2": "technophobe",
        "conflict3": "disciplined",
    },
    {"traitName": "loser", "conflict1": "brave", "conflict2": "charismatic"},
    {
        "traitName": "coward",
        "conflict1": "brave",
        "conflict2": "daredevil",
    },
    {"traitName": "artistic", "conflict1": "can't stand art"},
    {"traitName": "savvy sculptor", "conflict1": "can't stand art"},
    {
        "traitName": "easily impressed",
        "conflict1": "can't stand art",
        "conflict2": "snob",
    },
    {"traitName": "hopeless romantic", "conflict1": "commitment issues"},
    {
        "traitName": "technophobe",
        "conflict1": "computer whiz",
        "conflict2": "couch potato",
    },
    {"traitName": "athletic", "conflict1": "couch potato"},
    {"traitName": "disciplined", "conflict1": "couch potato"},
    {"traitName": "daredevil", "conflict1": "coward"},
    {"traitName": "brave", "conflict1": "coward", "conflict2": "loser"},
    {"traitName": "childish", "conflict1": "dislikes children"},
    {"traitName": "family-oriented", "conflict1": "dislikes children"},
    {"traitName": "nurturing", "conflict1": "dislikes children"},
    {"traitName": "snob", "conflict1": "easily impressed"},
    {"traitName": "good", "conflict1": "evil"},
    {"traitName": "grumpy", "conflict1": "excitable", "conflict2": "hot-headed"},
    {
        "traitName": "dislikes children",
        "conflict1": "family-oriented",
        "conflict2": "childish",
        "conflict3": "nurturing",
    },
    {"traitName": "unflirty", "conflict1": "flirty"},
    {
        "traitName": "shy",
        "conflict1": "flirty",
        "conflict2": "party animal",
    },
    {"traitName": "mean-spirited", "conflict1": "friendly"},
    {"traitName": "evil", "conflict1": "good"},
    {"traitName": "no sense of humour", "conflict1": "good sense of humour"},
    {"traitName": "hot-headed", "conflict1": "grumpy"},
    {
        "traitName": "excitable",
        "conflict1": "grumpy",
    },
    {"traitName": "eco-friendly", "conflict1": "hates the outdoors"},
    {"traitName": "loves the outdoors", "conflict1": "hates the outdoors"},
    {"traitName": "light sleeper", "conflict1": "heavy sleeper"},
    {"traitName": "commitment issues", "conflict1": "hopeless romantic"},
    {"traitName": "heavy sleeper", "conflict1": "light sleeper"},
    {"traitName": "party animal", "conflict1": "loner", "conflict2": "shy"},
    {"traitName": "charismatic", "conflict1": "loser", "conflict2": "socially awkward"},
    {
        "traitName": "hates the outdoors",
        "conflict1": "loves the outdoors",
        "conflict2": "eco-friendly",
    },
    {"traitName": "unlucky", "conflict1": "lucky"},
    {"traitName": "friendly", "conflict1": "mean-spirited"},
    {
        "traitName": "slob",
        "conflict1": "neat",
    },
    {"traitName": "good sense of humour", "conflict1": "no sense of humour"},
    {
        "traitName": "loner",
        "conflict1": "party animal",
    },
    {"traitName": "absent-minded", "conflict1": "perceptive"},
    {"traitName": "schmoozer", "conflict1": "rebellious"},
    {"traitName": "rebellious", "conflict1": "schmoozer"},
    {"traitName": "neat", "conflict1": "slob"},
    {"traitName": "computer whiz", "conflict1": "technophobe"},
    {"traitName": "flirty", "conflict1": "unflirty", "conflict2": "shy"},
    {"traitName": "lucky", "conflict1": "unlucky"},
]

ADULT_CONFLICTS = [
    {"trait": "absent-minded", "conflict1": "perceptive"},
    {
        "trait": "animal lover",
        "conflict1": "dog person",
        "conflict2": "cat person",
        "conflict3": "equestrian",
    },
    {"trait": "artistic", "conflict1": "can't stand art"},
    {"trait": "athletic", "conflict1": "couch potato"},
    {
        "trait": "avant garde",
        "conflict1": "can't stand art",
        "conflict2": "easily impressed",
    },
    {"trait": "bot fan", "conflict1": "technophobe"},
    {"trait": "brave", "conflict1": "coward", "conflict2": "loser"},
    {"trait": "brooding", "conflict1": "excitable"},
    {
        "trait": "can't stand art",
        "conflict1": "artistic",
        "conflict2": "easily impressed",
        "conflict3": "savvy sculptor",
        "conflict4": "avant garde",
    },
    {
        "trait": "cat person",
        "conflict1": "animal lover",
        "conflict2": "dog person",
        "conflict3": "equestrian",
    },
    {"trait": "charismatic", "conflict1": "loser", "conflict2": "socially awkward"},
    {"trait": "childish", "conflict1": "dislikes children"},
    {"trait": "clumsy", "conflict1": "natural born performer"},
    {"trait": "commitment issues", "conflict1": "hopeless romantic"},
    {"trait": "computer whiz", "conflict1": "technophobe"},
    {
        "trait": "couch potato",
        "conflict1": "athletic",
        "conflict2": "technophobe",
        "conflict3": "disciplined",
    },
    {
        "trait": "coward",
        "conflict1": "brave",
        "conflict2": "daredevil",
        "conflict3": "natural born performer",
        "conflict4": "supernatural fan",
    },
    {"trait": "daredevil", "conflict1": "coward"},
    {"trait": "disciplined", "conflict1": "couch potato"},
    {
        "trait": "dislikes children",
        "conflict1": "family-oriented",
        "conflict2": "childish",
        "conflict3": "nurturing",
    },
    {
        "trait": "dog person",
        "conflict1": "animal lover",
        "conflict2": "cat person",
        "conflict3": "equestrian",
    },
    {
        "trait": "easily impressed",
        "conflict1": "can't stand art",
        "conflict2": "snob",
        "conflict3": "avant garde",
    },
    {"trait": "eco-friendly", "conflict1": "hates the outdoors"},
    {
        "trait": "equestrian",
        "conflict1": "animal lover",
        "conflict2": "cat person",
        "conflict3": "dog person",
    },
    {"trait": "evil", "conflict1": "good"},
    {"trait": "excitable", "conflict1": "grumpy", "conflict2": "brooding"},
    {"trait": "family-oriented", "conflict1": "dislikes children"},
    {"trait": "flirty", "conflict1": "unflirty", "conflict2": "shy"},
    {"trait": "friendly", "conflict1": "mean-spirited"},
    {"trait": "good", "conflict1": "evil"},
    {"trait": "good sense of humour", "conflict1": "no sense of humour"},
    {"trait": "grumpy", "conflict1": "excitable", "conflict2": "hot-headed"},
    {
        "trait": "hates the outdoors",
        "conflict1": "loves the outdoors",
        "conflict2": "eco-friendly",
        "conflict3": "sailor",
    },
    {"trait": "heavy sleeper", "conflict1": "light sleeper"},
    {"trait": "hopeless romantic", "conflict1": "commitment issues"},
    {"trait": "hot-headed", "conflict1": "grumpy"},
    {"trait": "hydrophobic", "conflict1": "loves to swim"},
    {"trait": "inappropriate", "conflict1": "proper"},
    {"trait": "light sleeper", "conflict1": "heavy sleeper"},
    {"trait": "loner", "conflict1": "party animal", "conflict2": "social butterfly"},
    {"trait": "loser", "conflict1": "brave", "conflict2": "charismatic"},
    {"trait": "loves the outdoors", "conflict1": "hates the outdoors"},
    {"trait": "loves to swim", "conflict1": "hydrophobic"},
    {"trait": "lucky", "conflict1": "unlucky"},
    {"trait": "mean-spirited", "conflict1": "friendly"},
    {"trait": "natural born performer", "conflict1": "coward", "conflict2": "clumsy"},
    {"trait": "neat", "conflict1": "slob"},
    {"trait": "no sense of humour", "conflict1": "good sense of humour"},
    {"trait": "nurturing", "conflict1": "dislikes children"},
    {"trait": "party animal", "conflict1": "loner", "conflict2": "shy"},
    {"trait": "perceptive", "conflict1": "absent-minded"},
    {"trait": "proper", "conflict1": "slob", "conflict2": "inappropriate"},
    {"trait": "rebellious", "conflict1": "schmoozer"},
    {"trait": "sailor", "conflict1": "hates the outdoors"},
    {"trait": "savvy sculptor", "conflict1": "can't stand art"},
    {"trait": "schmoozer", "conflict1": "rebellious"},
    {
        "trait": "shy",
        "conflict1": "flirty",
        "conflict2": "party animal",
        "conflict3": "social butterfly",
    },
    {"trait": "slob", "conflict1": "neat", "conflict2": "proper"},
    {"trait": "snob", "conflict1": "easily impressed"},
    {"trait": "social butterfly", "conflict1": "loner", "conflict2": "shy"},
    {"trait": "socially awkward", "conflict1": "charismatic"},
    {
        "trait": "supernatural fan",
        "conflict1": "coward",
        "conflict2": "supernatural sceptic",
    },
    {"trait": "supernatural sceptic", "conflict1": "supernatural fan"},
    {
        "trait": "technophobe",
        "conflict1": "computer whiz",
        "conflict2": "couch potato",
        "conflict3": "bot fan",
    },
    {"trait": "unflirty", "conflict1": "flirty"},
    {"trait": "unlucky", "conflict1": "lucky"},
]
