# Get personality - Neat, Outgoing, Active, Playful, Nice
def get_personality():
    personality = {"Neat": 0, "Outgoing": 0, "Active": 0, "Playful": 0, "Nice": 0}

    print("\nPersonality Values\n")
    for value in personality:
        personality[value] = int(input(f"Please enter value for {value}: "))

    return personality.values()

def personality_traits_all(neat, outgoing, active, playful, nice, traits):
    
    if neat >= 8:
        traits["artistic"] -= 10
        traits["clumsy"] -= 10
        traits["couch potato"] -= 10
        traits["easily impressed"] -= 10
        traits["eccentric"] += 10
        traits["friendly"] += 10
        traits["hates the outdoors"] += 10
        traits["heavy sleeper"] -= 10
        traits["light sleeper"] += 10
        traits["loves the cold"] += 10
        traits["loves the outdoors"] -= 10
        traits["perceptive"] += 10
        traits["sailor"] -= 10
        traits["slob"] -= 10
    if neat >= 5 and neat < 8:
        traits["absent-minded"] -= 10
        traits["athletic"] += 10
        traits["brave"] += 10
        traits["disciplined"] += 10
        traits["evil"] += 10
        traits["excitable"] -= 10
        traits["genius"] += 10
        traits["good"] -= 10
        traits["grumpy"] += 10
        traits["insane"] += 10
        traits["loner"] += 10
        traits["loves the heat"] -= 10
        traits["neurotic"] += 10
        traits["virtuoso"] -= 10
    if neat >= 3 and neat < 5:
        traits["absent-minded"] += 10
        traits["athletic"] -= 10
        traits["brave"] -= 10
        traits["disciplined"] -= 10
        traits["evil"] -= 10
        traits["excitable"] += 10
        traits["genius"] -= 10
        traits["good"] += 10
        traits["grumpy"] -= 10
        traits["insane"] -= 10
        traits["loner"] -= 10
        traits["loves the heat"] += 10
        traits["neurotic"] -= 10
        traits["virtuoso"] += 10
    if neat <= 2:
        traits["artistic"] += 10
        traits["clumsy"] += 10
        traits["couch potato"] += 10
        traits["easily impressed"] += 10
        traits["eccentric"] -= 10
        traits["friendly"] -= 10
        traits["hates the outdoors"] -= 10
        traits["heavy sleeper"] += 10
        traits["light sleeper"] -= 10
        traits["loves the cold"] -= 10
        traits["loves the outdoors"] += 10
        traits["perceptive"] -= 10
        traits["sailor"] += 10
        traits["slob"] += 10
        
    if outgoing >= 8:
        traits["absent-minded"] -= 10
        traits["brave"] += 10
        traits["couch potato"] += 10
        traits["disciplined"] -= 10
        traits["eccentric"] -= 10
        traits["excitable"] += 10
        traits["friendly"] += 10
        traits["grumpy"] -= 10
        traits["loner"] -= 10
        traits["loves the cold"] -= 10
        traits["loves the heat"] += 10
        traits["perceptive"] -= 10
        traits["sailor"] += 10
        traits["virtuoso"] += 10
    if outgoing >= 5 and outgoing < 8:
        traits["artistic"] += 10
        traits["athletic"] += 10
        traits["clumsy"] -= 10
        traits["easily impressed"] += 10
        traits["evil"] += 10
        traits["genius"] -= 10
        traits["good"] -= 10
        traits["hates the outdoors"] -= 10
        traits["heavy sleeper"] -= 10
        traits["insane"] += 10
        traits["light sleeper"] += 10
        traits["loves the outdoors"] += 10
        traits["neurotic"] += 10
        traits["slob"] += 10
    if outgoing >= 3 and outgoing < 5:
        traits["artistic"] -= 10
        traits["athletic"] -= 10
        traits["clumsy"] += 10
        traits["easily impressed"] -= 10
        traits["evil"] -= 10
        traits["genius"] += 10
        traits["good"] += 10
        traits["hates the outdoors"] += 10
        traits["heavy sleeper"] += 10
        traits["insane"] -= 10
        traits["light sleeper"] -= 10
        traits["loves the outdoors"] -= 10
        traits["neurotic"] -= 10
        traits["slob"] -= 10
    if outgoing <= 2:
        traits["absent-minded"] += 10
        traits["brave"] -= 10
        traits["couch potato"] -= 10
        traits["disciplined"] += 10
        traits["eccentric"] += 10
        traits["excitable"] -= 10
        traits["friendly"] -= 10
        traits["grumpy"] += 10
        traits["loner"] += 10
        traits["loves the cold"] += 10
        traits["loves the heat"] -= 10
        traits["perceptive"] += 10
        traits["sailor"] -= 10
        traits["virtuoso"] -= 10
        
    if active >= 8:
        traits["athletic"] += 10
        traits["brave"] += 10
        traits["couch potato"] -= 10
        traits["disciplined"] += 10
        traits["eccentric"] -= 10
        traits["evil"] += 10
        traits["genius"] -= 10
        traits["good"] -= 10
        traits["hates the outdoors"] -= 10
        traits["heavy sleeper"] -= 10
        traits["light sleeper"] += 10
        traits["loves the outdoors"] += 10
        traits["sailor"] += 10
        traits["slob"] -= 10
    if active >= 5 and active < 8:
        traits["absent-minded"] += 10
        traits["artistic"] -= 10
        traits["clumsy"] += 10
        traits["easily impressed"] += 10
        traits["excitable"] += 10
        traits["friendly"] += 10
        traits["grumpy"] -= 10
        traits["insane"] -= 10
        traits["loner"] -= 10
        traits["loves the cold"] -= 10
        traits["loves the heat"] += 10 
        traits["neurotic"] -= 10
        traits["perceptive"] -= 10
        traits["virtuoso"] += 10
    if active >= 3 and active < 5:
        traits["absent-minded"] -= 10
        traits["artistic"] += 10
        traits["clumsy"] -= 10
        traits["easily impressed"] -= 10
        traits["excitable"] -= 10
        traits["friendly"] -= 10
        traits["grumpy"] += 10
        traits["insane"] += 10
        traits["loner"] += 10
        traits["loves the cold"] += 10
        traits["loves the heat"] -= 10
        traits["neurotic"] += 10
        traits["perceptive"] += 10
        traits["virtuoso"] -= 10
    if active <= 2:
        traits["athletic"] -= 10
        traits["brave"] -= 10
        traits["couch potato"] += 10
        traits["disciplined"] -= 10
        traits["eccentric"] += 10
        traits["evil"] -= 10
        traits["genius"] += 10
        traits["good"] += 10
        traits["hates the outdoors"] += 10
        traits["heavy sleeper"] += 10
        traits["light sleeper"] -= 10
        traits["loves the outdoors"] -= 10
        traits["sailor"] -= 10
        traits["slob"] += 10
        
    if playful >= 8:
        traits["absent-minded"] += 10
        traits["athletic"] -= 10
        traits["brave"] -= 10
        traits["clumsy"] += 10
        traits["eccentric"] -= 10
        traits["evil"] -= 10
        traits["excitable"] += 10
        traits["genius"] -= 10
        traits["good"] += 10
        traits["heavy sleeper"] -= 10
        traits["light sleeper"] += 10
        traits["neurotic"] -= 10
        traits["perceptive"] -= 10
        traits["slob"] += 10
    if playful >= 5 and playful < 8:
        traits["artistic"] += 10
        traits["couch potato"] += 10
        traits["disciplined"] -= 10
        traits["easily impressed"] += 10
        traits["friendly"] += 10
        traits["grumpy"] -= 10
        traits["hates the outdoors"] -= 10
        traits["insane"] += 10
        traits["loner"] -= 10
        traits["loves the cold"] -= 10
        traits["loves the heat"] += 10
        traits["loves the outdoors"] += 10
        traits["sailor"] += 10
        traits["virtuoso"] -= 10
    if playful >= 3 and playful < 5:
        traits["artistic"] -= 10
        traits["couch potato"] -= 10
        traits["disciplined"] += 10
        traits["easily impressed"] -= 10
        traits["friendly"] -= 10
        traits["grumpy"] += 10
        traits["hates the outdoors"] += 10
        traits["insane"] -= 10
        traits["loner"] += 10
        traits["loves the cold"] += 10
        traits["loves the heat"] -= 10
        traits["loves the outdoors"] -= 10
        traits["sailor"] -= 10
        traits["virtuoso"] += 10
    if playful <= 2:
        traits["absent-minded"] -= 10
        traits["athletic"] += 10
        traits["brave"] += 10
        traits["clumsy"] -= 10
        traits["eccentric"] += 10
        traits["evil"] += 10
        traits["excitable"] -= 10
        traits["genius"] += 10
        traits["good"] -= 10
        traits["heavy sleeper"] += 10
        traits["light sleeper"] -= 10
        traits["neurotic"] += 10
        traits["perceptive"] += 10
        traits["slob"] -= 10
        
    if nice >= 8:
        traits["artistic"] += 10
        traits["athletic"] -= 10
        traits["clumsy"] += 10
        traits["easily impressed"] += 10
        traits["evil"] -= 10
        traits["excitable"] += 10
        traits["good"] += 10
        traits["grumpy"] -= 10
        traits["heavy sleeper"] += 10
        traits["insane"] -= 10
        traits["light sleeper"] -= 10
        traits["loves the cold"] -= 10
        traits["loves the heat"] += 10
        traits["neurotic"] -= 10
        traits["virtuoso"] += 10
    if nice >= 5 and nice < 8:
        traits["absent-minded"] += 10
        traits["brave"] -= 10
        traits["couch potato"] += 10
        traits["disciplined"] -= 10
        traits["eccentric"] -= 10
        traits["friendly"] += 10
        traits["genius"] -= 10
        traits["hates the outdoors"] -= 10
        traits["loner"] += 10
        traits["loves the outdoors"] += 10
        traits["perceptive"] += 10
        traits["sailor"] -= 10
        traits["slob"] -= 10
    if nice >= 3 and nice < 5:
        traits["absent-minded"] -= 10
        traits["brave"] += 10
        traits["couch potato"] -= 10
        traits["disciplined"] += 10
        traits["eccentric"] += 10
        traits["friendly"] -= 10
        traits["genius"] += 10
        traits["hates the outdoors"] += 10
        traits["loner"] -= 10
        traits["loves the outdoors"] -= 10
        traits["perceptive"] -= 10
        traits["sailor"] += 10
        traits["slob"] += 10
    if nice <= 2:
        traits["artistic"] -= 10
        traits["athletic"] += 10
        traits["clumsy"] -= 10
        traits["easily impressed"] -= 10
        traits["evil"] += 10
        traits["excitable"] -= 10
        traits["good"] -= 10
        traits["grumpy"] += 10
        traits["heavy sleeper"] -= 10
        traits["insane"] += 10
        traits["light sleeper"] += 10
        traits["loves the cold"] += 10
        traits["loves the heat"] -= 10
        traits["neurotic"] += 10
        traits["virtuoso"] -= 10


def personality_traits_child(neat, outgoing, active, playful, nice, traits):
    
    if neat >= 8:
        traits["adventurous"] -= 10
        traits["animal lover"] -= 10
        traits["bookworm"] += 10
        traits["cat person"] += 10
        traits["coward"] += 10
        traits["daredevil"] -= 10
        traits["dog person"] -= 10
        traits["eco-friendly"] += 10
        traits["family-oriented"] += 10
        traits["hydrophobic"] += 10
        traits["inappropriate"] -= 10
        traits["loves to swim"] -= 10
        traits["mean-spirited"] -= 10
        traits["neat"] += 10
        traits["never nude"] -= 10
        traits["over-emotional"] -= 10
        traits["party animal"] -= 10
        traits["perfectionist"] += 10
        traits["snob"] += 10
        traits["technophobe"] += 10
        traits["vegetarian"] += 10
    if neat >= 5 and neat < 8:
        traits["ambitious"] += 10
        traits["angler"] -= 10
        traits["bot fan"] += 10
        traits["can't stand art"] -= 10
        traits["computer whiz"] += 10
        traits["diva"] += 10
        traits["equestrian"] -= 10
        traits["frugal"] += 10
        traits["good sense of humour"] += 10
        traits["hot-headed"] -= 10
        traits["kleptomaniac"] -= 10
        traits["loser"] -= 10
        traits["lucky"] += 10
        traits["mooch"] += 10
        traits["night owl"] -= 10
        traits["no sense of humour"] -= 10
        traits["photographer's eye"] += 10
        traits["rebellious"] -= 10
        traits["shy"] += 10
        traits["star quality"] -= 10
        traits["supernatural fan"] += 10
        traits["unlucky"] -= 10
        traits["unstable"] -= 10
        traits["vehicle enthusiast"] -= 10
        traits["workaholic"] += 10
    if neat >= 3 and neat < 5:
        traits["ambitious"] -= 10
        traits["angler"] += 10
        traits["bot fan"] -= 10
        traits["can't stand art"] += 10
        traits["computer whiz"] -= 10
        traits["diva"] -= 10
        traits["equestrian"] += 10
        traits["frugal"] -= 10
        traits["good sense of humour"] -= 10
        traits["hot-headed"] += 10
        traits["kleptomaniac"] += 10
        traits["loser"] += 10
        traits["lucky"] -= 10
        traits["mooch"] -= 10
        traits["night owl"] += 10
        traits["no sense of humour"] += 10
        traits["photographer's eye"] -= 10
        traits["rebellious"] += 10
        traits["shy"] -= 10
        traits["star quality"] += 10
        traits["supernatural fan"] -= 10
        traits["unlucky"] += 10
        traits["unstable"] += 10
        traits["vehicle enthusiast"] += 10
        traits["workaholic"] -= 10
    if neat <= 2:
        traits["adventurous"] += 10
        traits["animal lover"] += 10
        traits["bookworm"] -= 10
        traits["cat person"] -= 10
        traits["coward"] -= 10
        traits["daredevil"] += 10
        traits["dog person"] += 10
        traits["eco-friendly"] -= 10
        traits["family-oriented"] -= 10
        traits["hydrophobic"] -= 10
        traits["inappropriate"] += 10
        traits["loves to swim"] += 10
        traits["mean-spirited"] += 10
        traits["neat"] -= 10
        traits["never nude"] += 10
        traits["over-emotional"] += 10
        traits["party animal"] += 10
        traits["perfectionist"] -= 10
        traits["snob"] -= 10
        traits["technophobe"] -= 10
        traits["vegetarian"] -= 10
        
    if outgoing >= 8:
        traits["adventurous"] += 10
        traits["angler"] -= 10
        traits["animal lover"] += 10
        traits["can't stand art"] -= 10
        traits["cat person"] -= 10
        traits["coward"] -= 10
        traits["daredevil"] += 10
        traits["diva"] += 10
        traits["dog person"] += 10
        traits["good sense of humour"] += 10
        traits["kleptomaniac"] += 10
        traits["lucky"] += 10
        traits["mean-spirited"] -= 10
        traits["neat"] -= 10
        traits["never nude"] -= 10
        traits["no sense of humour"] -= 10
        traits["over-emotional"] += 10
        traits["rebellious"] += 10
        traits["shy"] -= 10
        traits["technophobe"] += 10
        traits["unlucky"] -= 10
        traits["vehicle enthusiast"] += 10
    if outgoing >= 5 and outgoing < 8:
        traits["ambitious"] += 10
        traits["bookworm"] -= 10
        traits["bot fan"] -= 10
        traits["computer whiz"] -= 10
        traits["eco-friendly"] -= 10
        traits["equestrian"] += 10
        traits["family-oriented"] -= 10
        traits["frugal"] += 10
        traits["hot-headed"] -= 10
        traits["hydrophobic"] -= 10
        traits["inappropriate"] += 10
        traits["loser"] -= 10
        traits["loves to swim"] += 10
        traits["mean-spirited"] += 10
        traits["night owl"] += 10
        traits["party animal"] += 10
        traits["perfectionist"] -= 10
        traits["photographer's eye"] += 10
        traits["snob"] -= 10
        traits["star quality"] += 10
        traits["supernatural fan"] -= 10
        traits["unstable"] += 10
        traits["vegetarian"] -= 10
        traits["workaholic"] -= 10
    if outgoing >= 3 and outgoing < 5:
        traits["ambitious"] -= 10
        traits["bookworm"] += 10
        traits["bot fan"] += 10
        traits["computer whiz"] += 10
        traits["eco-friendly"] += 10
        traits["equestrian"] -= 10
        traits["family-oriented"] += 10
        traits["frugal"] -= 10
        traits["hot-headed"] += 10
        traits["hydrophobic"] += 10
        traits["inappropriate"] -= 10
        traits["loser"] += 10
        traits["loves to swim"] -= 10
        traits["mean-spirited"] -= 10
        traits["night owl"] -= 10
        traits["party animal"] -= 10
        traits["perfectionist"] += 10
        traits["photographer's eye"] -= 10
        traits["snob"] += 10
        traits["star quality"] -= 10
        traits["supernatural fan"] += 10
        traits["unstable"] -= 10
        traits["vegetarian"] += 10
        traits["workaholic"] += 10
    if outgoing <= 2:
        traits["adventurous"] -= 10
        traits["angler"] += 10
        traits["animal lover"] -= 10
        traits["can't stand art"] += 10
        traits["cat person"] += 10
        traits["coward"] += 10
        traits["daredevil"] -= 10
        traits["diva"] -= 10
        traits["dog person"] -= 10
        traits["good sense of humour"] -= 10
        traits["kleptomaniac"] -= 10
        traits["lucky"] -= 10
        traits["mean-spirited"] += 10
        traits["neat"] += 10
        traits["never nude"] += 10
        traits["no sense of humour"] += 10
        traits["over-emotional"] -= 10
        traits["rebellious"] -= 10
        traits["shy"] += 10
        traits["technophobe"] -= 10
        traits["unlucky"] += 10
        traits["vehicle enthusiast"] -= 10
        
    if active >= 8:
        traits["adventurous"] += 10
        traits["angler"] -= 10
        traits["bookworm"] -= 10
        traits["can't stand art"] -= 10
        traits["cat person"] -= 10
        traits["computer whiz"] -= 10
        traits["dog person"] += 10
        traits["hydrophobic"] -= 10
        traits["kleptomaniac"] += 10
        traits["loves to swim"] += 10
        traits["lucky"] += 10
        traits["neat"] -= 10
        traits["never nude"] -= 10
        traits["perfectionist"] -= 10
        traits["shy"] -= 10
        traits["snob"] += 10
        traits["star quality"] += 10
        traits["technophobe"] += 10
        traits["unlucky"] -= 10
        traits["vegetarian"] += 10
        traits["workaholic"] += 10
    if active >= 5 and active < 8:
        traits["ambitious"] += 10
        traits["animal lover"] += 10
        traits["bot fan"] -= 10
        traits["coward"] -= 10
        traits["daredevil"] += 10
        traits["diva"] += 10
        traits["eco-friendly"] += 10
        traits["equestrian"] += 10
        traits["family-oriented"] -= 10
        traits["frugal"] -= 10
        traits["good sense of humour"] -= 10
        traits["hot-headed"] += 10
        traits["inappropriate"] -= 10
        traits["loser"] -= 10
        traits["mean-spirited"] += 10
        traits["mooch"] -= 10
        traits["night owl"] += 10
        traits["no sense of humour"] += 10
        traits["over-emotional"] += 10
        traits["party animal"] += 10
        traits["photographer's eye"] -= 10
        traits["rebellious"] += 10
        traits["supernatural fan"] -= 10
        traits["unstable"] -= 10
        traits["vehicle enthusiast"] -= 10
    if active >= 3 and active < 5:
        traits["ambitious"] -= 10
        traits["animal lover"] -= 10
        traits["bot fan"] += 10
        traits["coward"] += 10
        traits["daredevil"] -= 10
        traits["diva"] -= 10
        traits["eco-friendly"] -= 10
        traits["equestrian"] -= 10
        traits["family-oriented"] += 10
        traits["frugal"] += 10
        traits["good sense of humour"] += 10
        traits["hot-headed"] -= 10
        traits["inappropriate"] += 10
        traits["loser"] += 10
        traits["mean-spirited"] -= 10
        traits["mooch"] += 10
        traits["night owl"] -= 10
        traits["no sense of humour"] -= 10
        traits["over-emotional"] -= 10
        traits["party animal"] -= 10
        traits["photographer's eye"] += 10
        traits["rebellious"] -= 10
        traits["supernatural fan"] += 10
        traits["unstable"] += 10
        traits["vehicle enthusiast"] += 10
    if active <= 2:
        traits["adventurous"] -= 10
        traits["angler"] += 10
        traits["bookworm"] += 10
        traits["can't stand art"] += 10
        traits["cat person"] += 10
        traits["computer whiz"] += 10
        traits["dog person"] -= 10
        traits["hydrophobic"] += 10
        traits["kleptomaniac"] -= 10
        traits["loves to swim"] -= 10
        traits["lucky"] -= 10
        traits["neat"] += 10
        traits["never nude"] += 10
        traits["perfectionist"] += 10
        traits["shy"] += 10
        traits["snob"] -= 10
        traits["star quality"] -= 10
        traits["technophobe"] -= 10
        traits["unlucky"] += 10
        traits["vegetarian"] -= 10
        traits["workaholic"] -= 10
        
    if playful >= 8:
        traits["ambitious"] -= 10
        traits["angler"] -= 10
        traits["animal lover"] += 10
        traits["bot fan"] -= 10
        traits["computer whiz"] -= 10
        traits["diva"] -= 10
        traits["dog person"] += 10
        traits["family-oriented"] += 10
        traits["hydrophobic"] -= 10
        traits["loser"] += 10
        traits["loves to swim"] += 10
        traits["mean-spirited"] -= 10
        traits["mooch"] -= 10
        traits["never nude"] -= 10
        traits["night owl"] += 10
        traits["over-emotional"] += 10
        traits["perfectionist"] -= 10
        traits["snob"] -= 10
        traits["star quality"] += 10
        traits["supernatural fan"] -= 10
        traits["vegetarian"] -= 10
        traits["workaholic"] -= 10
    if playful >= 5 and playful < 8:
        traits["adventurous"] -= 10
        traits["bookworm"] -= 10
        traits["can't stand art"] -= 10
        traits["cat person"] -= 10
        traits["coward"] += 10
        traits["daredevil"] += 10
        traits["eco-friendly"] -= 10
        traits["equestrian"] -= 10
        traits["frugal"] -= 10
        traits["good sense of humour"] += 10
        traits["hot-headed"] -= 10
        traits["inappropriate"] += 10
        traits["kleptomaniac"] -= 10
        traits["lucky"] -= 10
        traits["neat"] -= 10
        traits["no sense of humour"] -= 10
        traits["party animal"] += 10
        traits["photographer's eye"] += 10
        traits["rebellious"] -= 10
        traits["shy"] -= 10
        traits["technophobe"] += 10
        traits["unlucky"] += 10
        traits["unstable"] += 10
        traits["vehicle enthusiast"] += 10
    if playful >= 3 and playful < 5:
        traits["adventurous"] += 10
        traits["bookworm"] += 10
        traits["can't stand art"] += 10
        traits["cat person"] += 10
        traits["coward"] -= 10
        traits["daredevil"] -= 10
        traits["eco-friendly"] += 10
        traits["equestrian"] += 10
        traits["frugal"] += 10
        traits["good sense of humour"] -= 10
        traits["hot-headed"] += 10
        traits["inappropriate"] -= 10
        traits["kleptomaniac"] += 10
        traits["lucky"] += 10
        traits["neat"] += 10
        traits["no sense of humour"] += 10
        traits["party animal"] -= 10
        traits["photographer's eye"] -= 10
        traits["rebellious"] += 10
        traits["shy"] += 10
        traits["technophobe"] -= 10
        traits["unlucky"] -= 10
        traits["unstable"] -= 10
        traits["vehicle enthusiast"] -= 10
    if playful <= 2:
        traits["ambitious"] += 10
        traits["angler"] += 10
        traits["animal lover"] -= 10
        traits["bot fan"] += 10
        traits["computer whiz"] += 10
        traits["diva"] += 10
        traits["dog person"] -= 10
        traits["family-oriented"] -= 10
        traits["hydrophobic"] += 10
        traits["loser"] -= 10
        traits["loves to swim"] -= 10
        traits["mean-spirited"] += 10
        traits["mooch"] += 10
        traits["never nude"] += 10
        traits["night owl"] -= 10
        traits["over-emotional"] -= 10
        traits["perfectionist"] += 10
        traits["snob"] += 10
        traits["star quality"] -= 10
        traits["supernatural fan"] += 10
        traits["vegetarian"] += 10
        traits["workaholic"] += 10
        
    if nice >= 8:
        traits["ambitious"] -= 10
        traits["animal lover"] += 10
        traits["can't stand art"] -= 10
        traits["coward"] += 10
        traits["daredevil"] -= 10
        traits["diva"] -= 10
        traits["dog person"] += 10
        traits["family-oriented"] += 10
        traits["good sense of humour"] += 10
        traits["hot-headed"] -= 10
        traits["inappropriate"] -= 10
        traits["kleptomaniac"] -= 10
        traits["mean-spirited"] -= 10
        traits["never nude"] += 10
        traits["night owl"] -= 10
        traits["no sense of humour"] -= 10
        traits["perfectionist"] -= 10
        traits["photographer's eye"] += 10
        traits["shy"] += 10
        traits["supernatural fan"] += 10
        traits["unstable"] -= 10
        traits["workaholic"] -= 10
    if nice >= 5 and nice < 8:
        traits["adventurous"] -= 10
        traits["angler"] += 10
        traits["bookworm"] -= 10
        traits["bot fan"] -= 10
        traits["cat person"] += 10
        traits["computer whiz"] += 10
        traits["eco-friendly"] += 10
        traits["equestrian"] -= 10
        traits["frugal"] -= 10
        traits["hydrophobic"] -= 10
        traits["loser"] -= 10
        traits["loves to swim"] += 10
        traits["lucky"] += 10
        traits["mooch"] -= 10
        traits["neat"] -= 10
        traits["over-emotional"] += 10
        traits["party animal"] -= 10
        traits["rebellious"] -= 10
        traits["snob"] -= 10
        traits["star quality"] -= 10
        traits["technophobe"] -= 10
        traits["unlucky"] -= 10
        traits["vegetarian"] += 10
        traits["vehicle enthusiast"] -= 10
    if nice >= 3 and nice < 5:
        traits["adventurous"] += 10
        traits["angler"] -= 10
        traits["bookworm"] += 10
        traits["bot fan"] += 10
        traits["cat person"] -= 10
        traits["computer whiz"] -= 10
        traits["eco-friendly"] -= 10
        traits["equestrian"] += 10
        traits["frugal"] += 10
        traits["hydrophobic"] += 10
        traits["loser"] += 10
        traits["loves to swim"] -= 10
        traits["lucky"] -= 10
        traits["mooch"] += 10
        traits["neat"] += 10
        traits["over-emotional"] -= 10
        traits["party animal"] += 10
        traits["rebellious"] += 10
        traits["snob"] += 10
        traits["star quality"] += 10
        traits["technophobe"] += 10
        traits["unlucky"] += 10
        traits["vegetarian"] -= 10
        traits["vehicle enthusiast"] += 10
    if nice <= 2:
        traits["ambitious"] += 10
        traits["animal lover"] -= 10
        traits["can't stand art"] += 10
        traits["coward"] -= 10
        traits["daredevil"] += 10
        traits["diva"] += 10
        traits["dog person"] -= 10
        traits["family-oriented"] -= 10
        traits["good sense of humour"] -= 10
        traits["hot-headed"] += 10
        traits["inappropriate"] += 10
        traits["kleptomaniac"] += 10
        traits["mean-spirited"] += 10
        traits["never nude"] -= 10
        traits["night owl"] += 10
        traits["no sense of humour"] += 10
        traits["perfectionist"] += 10
        traits["photographer's eye"] -= 10
        traits["shy"] -= 10
        traits["supernatural fan"] -= 10
        traits["unstable"] += 10
        traits["workaholic"] += 10

def personality_traits_teen(neat, outgoing, active, playful, nice, traits):   
    if neat >= 8:
        traits["avant garde"] -= 10
        traits["charismatic"] -= 10
        traits["commitment issues"] -= 10
        traits["dramatic"] -= 10
        traits["gatherer"] -= 10
        traits["green thumb"] -= 10
        traits["hopeless romantic"] += 10
        traits["natural born performer"] -= 10
        traits["nurturing"] += 10
        traits["proper"] += 10
        traits["savvy sculptor"] -= 10
        traits["social butterfly"] -= 10
        traits["socially awkward"] += 10
    if neat >= 5 and neat < 8:
        traits["born salesman"] -= 10
        traits["brooding"] -= 10
        traits["childish"] -= 10
        traits["dislikes children"] += 10
        traits["flirty"] -= 10
        traits["great kisser"] -= 10
        traits["handy"] += 10
        traits["irresistible"] -= 10
        traits["natural cook"] += 10
        traits["schmoozer"] -= 10
        traits["supernatural sceptic"] -= 10
    if neat >= 3 and neat < 5:
        traits["born salesman"] += 10
        traits["brooding"] += 10
        traits["childish"] += 10
        traits["dislikes children"] -= 10
        traits["flirty"] += 10
        traits["great kisser"] += 10
        traits["handy"] -= 10
        traits["irresistible"] += 10
        traits["natural cook"] -= 10
        traits["schmoozer"] += 10
        traits["supernatural sceptic"] += 10
    if neat <= 2:
        traits["avant garde"] += 10
        traits["charismatic"] += 10
        traits["commitment issues"] += 10
        traits["dramatic"] += 10
        traits["gatherer"] += 10
        traits["green thumb"] += 10
        traits["hopeless romantic"] -= 10
        traits["natural born performer"] += 10
        traits["nurturing"] -= 10
        traits["proper"] -= 10
        traits["savvy sculptor"] += 10
        traits["social butterfly"] += 10
        traits["socially awkward"] -= 10
        
    if outgoing >= 8:
        traits["born salesman"] += 10
        traits["brooding"] -= 10
        traits["charismatic"] += 10
        traits["commitment issues"] += 10
        traits["flirty"] += 10
        traits["green thumb"] -= 10
        traits["handy"] -= 10
        traits["irresistible"] += 10
        traits["natural born performer"] += 10
        traits["schmoozer"] += 10
        traits["social butterfly"] += 10
        traits["socially awkward"] -= 10
    if outgoing >= 5 and outgoing < 8:
        traits["avant garde"] += 10
        traits["childish"] += 10
        traits["dislikes children"] += 10
        traits["dramatic"] += 10
        traits["gatherer"] -= 10
        traits["great kisser"] += 10
        traits["hopeless romantic"] -= 10
        traits["natural cook"] += 10
        traits["nurturing"] -= 10
        traits["proper"] -= 10
        traits["savvy sculptor"] += 10
        traits["supernatural sceptic"] += 10
    if outgoing >= 3 and outgoing < 5:
        traits["avant garde"] -= 10
        traits["childish"] -= 10
        traits["dislikes children"] -= 10
        traits["dramatic"] -= 10
        traits["gatherer"] += 10
        traits["great kisser"] -= 10
        traits["hopeless romantic"] += 10
        traits["natural cook"] -= 10
        traits["nurturing"] += 10
        traits["proper"] += 10
        traits["savvy sculptor"] -= 10
        traits["supernatural sceptic"] -= 10
    if outgoing <= 2:
        traits["born salesman"] -= 10
        traits["brooding"] += 10
        traits["charismatic"] -= 10
        traits["commitment issues"] -= 10
        traits["flirty"] -= 10
        traits["green thumb"] += 10
        traits["handy"] += 10
        traits["irresistible"] -= 10
        traits["natural born performer"] -= 10
        traits["schmoozer"] -= 10
        traits["social butterfly"] -= 10
        traits["socially awkward"] += 10
        
    if active >= 8:
        traits["brooding"] -= 10
        traits["commitment issues"] += 10
        traits["dislikes children"] += 10
        traits["dramatic"] += 10
        traits["great kisser"] += 10
        traits["green thumb"] += 10
        traits["irresistible"] += 10
        traits["natural born performer"] += 10
        traits["proper"] -= 10
    if active >= 5 and active < 8:
        traits["avant garde"] -= 10
        traits["born salesman"] -= 10
        traits["charismatic"] += 10
        traits["childish"] += 10
        traits["flirty"] += 10
        traits["gatherer"] += 10
        traits["handy"] -= 10
        traits["hopeless romantic"] += 10
        traits["natural cook"] += 10
        traits["nurturing"] -= 10
        traits["savvy sculptor"] -= 10
        traits["schmoozer"] += 10
        traits["social butterfly"] += 10
        traits["socially awkward"] -= 10
        traits["supernatural sceptic"] += 10
    if active >= 3 and active < 5:
        traits["avant garde"] += 10
        traits["born salesman"] += 10
        traits["charismatic"] -= 10
        traits["childish"] -= 10
        traits["flirty"] -= 10
        traits["gatherer"] -= 10
        traits["handy"] += 10
        traits["hopeless romantic"] -= 10
        traits["natural cook"] -= 10
        traits["nurturing"] += 10
        traits["savvy sculptor"] += 10
        traits["schmoozer"] -= 10
        traits["social butterfly"] -= 10
        traits["socially awkward"] += 10
        traits["supernatural sceptic"] -= 10
    if active <= 2:
        traits["brooding"] += 10
        traits["commitment issues"] -= 10
        traits["dislikes children"] -= 10
        traits["dramatic"] -= 10
        traits["great kisser"] -= 10
        traits["green thumb"] -= 10
        traits["irresistible"] -= 10
        traits["natural born performer"] -= 10
        traits["proper"] += 10
        
    if playful >= 8:
        traits["born salesman"] -= 10
        traits["brooding"] -= 10
        traits["childish"] += 10
        traits["dramatic"] -= 10
        traits["flirty"] -= 10
        traits["gatherer"] -= 10
        traits["handy"] += 10
        traits["hopeless romantic"] += 10
        traits["natural cook"] -= 10
        traits["nurturing"] += 10
        traits["supernatural sceptic"] += 10
    if playful >= 5 and playful < 8:
        traits["avant garde"] += 10
        traits["charismatic"] += 10
        traits["commitment issues"] += 10
        traits["dislikes children"] -= 10
        traits["great kisser"] += 10
        traits["green thumb"] -= 10
        traits["irresistible"] -= 10
        traits["natural born performer"] -= 10
        traits["proper"] -= 10
        traits["savvy sculptor"] += 10
        traits["schmoozer"] += 10
        traits["social butterfly"] += 10
        traits["socially awkward"] -= 10
    if playful >= 3 and playful < 5:
        traits["avant garde"] -= 10
        traits["charismatic"] -= 10
        traits["commitment issues"] -= 10
        traits["dislikes children"] += 10
        traits["great kisser"] -= 10
        traits["green thumb"] += 10
        traits["irresistible"] += 10
        traits["natural born performer"] += 10
        traits["proper"] += 10
        traits["savvy sculptor"] -= 10
        traits["schmoozer"] -= 10
        traits["social butterfly"] -= 10
        traits["socially awkward"] += 10
    if playful <= 2:
        traits["born salesman"] += 10
        traits["brooding"] += 10
        traits["childish"] -= 10
        traits["dramatic"] += 10
        traits["flirty"] += 10
        traits["gatherer"] += 10
        traits["handy"] -= 10
        traits["hopeless romantic"] -= 10
        traits["natural cook"] += 10
        traits["nurturing"] -= 10
        traits["supernatural sceptic"] -= 10
        
    if nice >= 8:
        traits["avant garde"] += 10
        traits["born salesman"] -= 10
        traits["brooding"] -= 10
        traits["commitment issues"] -= 10
        traits["dislikes children"] -= 10
        traits["handy"] += 10
        traits["hopeless romantic"] += 10
        traits["natural born performer"] += 10
        traits["natural cook"] += 10
        traits["savvy sculptor"] += 10
        traits["supernatural sceptic"] -= 10
    if nice >= 5 and nice < 8:
        traits["charismatic"] -= 10
        traits["childish"] += 10
        traits["dramatic"] -= 10
        traits["flirty"] += 10
        traits["gatherer"] += 10
        traits["great kisser"] += 10
        traits["green thumb"] += 10
        traits["irresistible"] += 10
        traits["nurturing"] += 10
        traits["proper"] -= 10
        traits["schmoozer"] -= 10
        traits["social butterfly"] -= 10
        traits["socially awkward"] += 10
    if nice >= 3 and nice < 5:
        traits["charismatic"] += 10
        traits["childish"] -= 10
        traits["dramatic"] += 10
        traits["flirty"] -= 10
        traits["gatherer"] -= 10
        traits["great kisser"] -= 10
        traits["green thumb"] -= 10
        traits["irresistible"] -= 10
        traits["nurturing"] -= 10
        traits["proper"] += 10
        traits["schmoozer"] += 10
        traits["social butterfly"] += 10
        traits["socially awkward"] -= 10
    if nice <= 2:
        traits["avant garde"] -= 10
        traits["born salesman"] += 10
        traits["brooding"] += 10
        traits["commitment issues"] += 10
        traits["dislikes children"] += 10
        traits["handy"] -= 10
        traits["hopeless romantic"] -= 10
        traits["natural born performer"] -= 10
        traits["natural cook"] -= 10
        traits["savvy sculptor"] -= 10
        traits["supernatural sceptic"] += 10
