from globals import TURN_ONS_OFF
import inquirer3
from inquirer3 import Checkbox, List, errors


def validate_turn_ons(answers, current):
    if len(current) != 2:
        raise errors.ValidationError(
            "Custom validation failed", reason="Please select exactly 2 turn ons"
        )
    else:
        return True


def get_turn_ons_off():

    turn_ons = [
        Checkbox(
            "turn_ons",
            message="Select 2 turn ons: ",
            choices=TURN_ONS_OFF,
            validate=validate_turn_ons,
        )
    ]

    turn_off = [List("turn_off", message="Select 1 turn off", choices=TURN_ONS_OFF)]

    turn_on_answers = None

    while not turn_on_answers:
        try:
            turn_on_answers = inquirer3.prompt(turn_ons)
            print("You selected:", turn_on_answers["turn_ons"])
            break
        except errors.ValidationError as e:
            print(f"Error: {e.reason}")
            break

    turn_off_answer = None

    turn_off_answer = inquirer3.prompt(turn_off)

    # Check if any input is None and handle it
    if turn_on_answers is None:
        turn_on_answers = {"turn_ons": []}
    if turn_off_answer is None:
        turn_off_answer = {"turn_off": ""}

    return turn_on_answers, turn_off_answer


def get_trait_turn_off(turn_off, traits):
    # Turn Off
    match (turn_off):
        case "Adventurous":
            traits["absent-minded"] += 20
            traits["adventurous"] -= 20
            traits["ambitious"] -= 20
            traits["athletic"] -= 20
            traits["born salesman"] -= 20
            traits["brave"] -= 20
            traits["brooding"] += 20
            traits["charismatic"] -= 20
            traits["clumsy"] += 20
            traits["commitment issues"] += 20
            traits["couch potato"] += 20
            traits["coward"] += 20
            traits["daredevil"] -= 20
            traits["diva"] += 20
            traits["dramatic"] += 20
            traits["easily impressed"] += 20
            traits["evil"] -= 20
            traits["excitable"] -= 20
            traits["flirty"] += 20
            traits["friendly"] += 20
            traits["gatherer"] -= 20
            traits["grumpy"] += 20
            traits["hates the outdoors"] += 20
            traits["heavy sleeper"] += 20
            traits["hydrophobic"] += 20
            traits["inappropriate"] += 20
            traits["insane"] += 20
            traits["irresistible"] += 20
            traits["kleptomaniac"] -= 20
            traits["light sleeper"] -= 20
            traits["loner"] += 20
            traits["loser"] += 20
            traits["loves the cold"] += 20
            traits["loves the heat"] -= 20
            traits["loves the outdoors"] -= 20
            traits["lucky"] -= 20
            traits["neurotic"] += 20
            traits["never nude"] += 20
            traits["shy"] += 20
            traits["social butterfly"] -= 20
            traits["socially awkward"] += 20
            traits["supernatural fan"] -= 20
            traits["supernatural sceptic"] += 20
            traits["unlucky"] += 20
            traits["unstable"] += 20
        case "Alien":
            traits["absent-minded"] += 20
            traits["adventurous"] -= 20
            traits["ambitious"] -= 20
            traits["bookworm"] -= 20
            traits["bot fan"] -= 20
            traits["brave"] -= 20
            traits["brooding"] += 20
            traits["commitment issues"] += 20
            traits["coward"] -= 20
            traits["diva"] += 20
            traits["dramatic"] += 20
            traits["evil"] += 20
            traits["flirty"] += 20
            traits["grumpy"] += 20
            traits["inappropriate"] += 20
            traits["insane"] += 20
            traits["irresistible"] += 20
            traits["mean-spirited"] += 20
            traits["night owl"] -= 20
            traits["proper"] += 20
            traits["rebellious"] += 20
            traits["shy"] -= 20
            traits["social butterfly"] += 20
            traits["socially awkward"] -= 20
            traits["supernatural fan"] -= 20
            traits["supernatural sceptic"] += 20
        case "Animal Lover":
            traits["animal lover"] -= 20
            traits["cat person"] -= 20
            traits["dog person"] -= 20
            traits["equestrian"] -= 20
            traits["evil"] += 20
            traits["family-oriented"] -= 20
            traits["grumpy"] += 20
            traits["inappropriate"] += 20
            traits["insane"] += 20
            traits["kleptomaniac"] += 20
            traits["neat"] += 20
            traits["socially awkward"] += 20
        case "Artistic":
            traits["absent-minded"] += 20
            traits["ambitious"] -= 20
            traits["artistic"] -= 20
            traits["avant garde"] -= 20
            traits["brooding"] += 20
            traits["can't stand art"] += 20
            traits["eccentric"] += 20
            traits["evil"] += 20
            traits["photographer's eye"] -= 20
            traits["savvy sculptor"] -= 20
            traits["star quality"] -= 20
            traits["virtuoso"] -= 20
        case "Athletic":
            traits["ambitious"] -= 20
            traits["athletic"] -= 20
            traits["daredevil"] -= 20
            traits["disciplined"] -= 20
            traits["equestrian"] -= 20
            traits["hydrophobic"] += 20
            traits["loves to swim"] -= 20
            traits["sailor"] -= 20
        case "Business Shark":
            traits["absent-minded"] += 20
            traits["ambitious"] -= 20
            traits["born salesman"] -= 20
            traits["easily impressed"] += 20
            traits["excitable"] += 20
            traits["family-oriented"] += 20
            traits["friendly"] += 20
            traits["good"] += 20
            traits["good sense of humour"] += 20
            traits["grumpy"] -= 20
            traits["heavy sleeper"] += 20
            traits["light sleeper"] -= 20
            traits["mean-spirited"] -= 20
            traits["nurturing"] += 20
            traits["schmoozer"] -= 20
            traits["shy"] += 20
            traits["snob"] -= 20
            traits["star quality"] -= 20
            traits["workaholic"] -= 20
        case "Charismatic":
            traits["brooding"] += 20
            traits["charismatic"] -= 20
            traits["diva"] -= 20
            traits["dramatic"] -= 20
            traits["excitable"] -= 20
            traits["flirty"] -= 20
            traits["friendly"] -= 20
            traits["good"] -= 20
            traits["good sense of humour"] -= 20
            traits["grumpy"] += 20
            traits["hopeless romantic"] -= 20
            traits["hot-headed"] += 20
            traits["inappropriate"] += 20
            traits["insane"] += 20
            traits["irresistible"] -= 20
            traits["light sleeper"] -= 20
            traits["loner"] += 20
            traits["loser"] += 20
            traits["mean-spirited"] += 20
            traits["natural born performer"] -= 20
            traits["no sense of humour"] += 20
            traits["rebellious"] += 20
            traits["schmoozer"] -= 20
            traits["shy"] += 20
            traits["social butterfly"] -= 20
            traits["socially awkward"] += 20
            traits["star quality"] -= 20
        case "Cultured":
            traits["absent-minded"] += 20
            traits["artistic"] -= 20
            traits["avant garde"] -= 20
            traits["bookworm"] -= 20
            traits["born salesman"] += 20
            traits["bot fan"] += 20
            traits["can't stand art"] += 20
            traits["couch potato"] -= 20
            traits["diva"] -= 20
            traits["loves the cold"] -= 20
            traits["loves the heat"] += 20
            traits["photographer's eye"] -= 20
            traits["savvy sculptor"] -= 20
            traits["snob"] += 20
            traits["technophobe"] += 20
            traits["virtuoso"] -= 20
        case "Expressive":
            traits["adventurous"] -= 20
            traits["artistic"] -= 20
            traits["avant garde"] -= 20
            traits["bookworm"] += 20
            traits["brooding"] += 20
            traits["charismatic"] -= 20
            traits["childish"] -= 20
            traits["diva"] -= 20
            traits["dramatic"] -= 20
            traits["excitable"] -= 20
            traits["grumpy"] += 20
            traits["loner"] += 20
            traits["loser"] += 20
            traits["mean-spirited"] += 20
            traits["neurotic"] += 20
            traits["no sense of humour"] += 20
            traits["over-emotional"] -= 20
            traits["party animal"] -= 20
            traits["rebellious"] += 20
            traits["shy"] += 20
            traits["social butterfly"] -= 20
            traits["socially awkward"] += 20
        case "Fatness":
            traits["adventurous"] += 20
            traits["athletic"] += 20
            traits["couch potato"] -= 20
            traits["disciplined"] += 20
            traits["equestrian"] += 20
            traits["loves the cold"] -= 20
            traits["loves the heat"] += 20
            traits["hates the outdoors"] -= 20
            traits["heavy sleeper"] -= 20
            traits["light sleeper"] += 20
            traits["loves the outdoors"] += 20
            traits["loves to swim"] += 20
            traits["never nude"] -= 20
            traits["sailor"] += 20
            traits["slob"] -= 20
            traits["vegetarian"] += 20
        case "Fitness":
            traits["athletic"] -= 20
            traits["couch potato"] += 20
            traits["disciplined"] -= 20
            traits["hates the outdoors"] += 20
            traits["heavy sleeper"] += 20
            traits["hydrophobic"] += 20
            traits["light sleeper"] -= 20
            traits["loves the cold"] += 20
            traits["loves the heat"] -= 20
            traits["loves the outdoors"] -= 20
            traits["loves to swim"] -= 20
            traits["sailor"] -= 20
            traits["vegetarian"] -= 20
        case "Foodie":
            traits["artistic"] -= 20
            traits["can't stand art"] += 20
            traits["clumsy"] += 20
            traits["evil"] += 20
            traits["family-oriented"] -= 20
            traits["grumpy"] += 20
            traits["hot-headed"] += 20
            traits["irresistible"] += 20
            traits["mean-spirited"] += 20
            traits["natural cook"] -= 20
            traits["neat"] -= 20
            traits["nurturing"] -= 20
            traits["rebellious"] += 20
            traits["slob"] += 20
            traits["snob"] -= 20
            traits["vegetarian"] -= 20
        case "Indoorsy":
            traits["adventurous"] += 20
            traits["angler"] += 20
            traits["bookworm"] -= 20
            traits["bot fan"] -= 20
            traits["computer whiz"] -= 20
            traits["couch potato"] -= 20
            traits["eco-friendly"] += 20
            traits["equestrian"] += 20
            traits["gatherer"] += 20
            traits["green thumb"] += 20
            traits["hates the outdoors"] -= 20
            traits["loves the cold"] -= 20
            traits["loves the heat"] += 20
            traits["loves the outdoors"] += 20
            traits["night owl"] -= 20
            traits["sailor"] += 20
            traits["shy"] -= 20
            traits["technophobe"] += 20
            traits["vehicle enthusiast"] += 20
        case "Infamous":
            traits["animal lover"] += 20
            traits["avant garde"] -= 20
            traits["charismatic"] += 20
            traits["childish"] += 20
            traits["commitment issues"] -= 20
            traits["coward"] += 20
            traits["daredevil"] -= 20
            traits["disciplined"] += 20
            traits["dislikes children"] -= 20
            traits["diva"] -= 20
            traits["dramatic"] -= 20
            traits["easily impressed"] += 20
            traits["evil"] -= 20
            traits["excitable"] -= 20
            traits["family-oriented"] += 20
            traits["friendly"] += 20
            traits["good"] += 20
            traits["hopeless romantic"] += 20
            traits["inappropriate"] -= 20
            traits["insane"] -= 20
            traits["lucky"] += 20
            traits["mean-spirited"] -= 20
            traits["natural cook"] += 20
            traits["neat"] += 20
            traits["nurturing"] += 20
            traits["over-emotional"] += 20
            traits["perceptive"] += 20
            traits["perfectionist"] += 20
            traits["proper"] += 20
            traits["rebellious"] -= 20
            traits["shy"] += 20
            traits["supernatural fan"] += 20
            traits["supernatural sceptic"] -= 20
            traits["unlucky"] -= 20
            traits["unstable"] -= 20
        case "Intellect":
            traits["absent-minded"] += 20
            traits["ambitious"] += 20
            traits["artistic"] += 20
            traits["bookworm"] -= 20
            traits["brooding"] -= 20
            traits["childish"] += 20
            traits["commitment issues"] += 20
            traits["computer whiz"] -= 20
            traits["diva"] += 20
            traits["dramatic"] += 20
            traits["easily impressed"] += 20
            traits["evil"] += 20
            traits["excitable"] += 20
            traits["genius"] -= 20
            traits["grumpy"] -= 20
            traits["hates the outdoors"] -= 20
            traits["hopeless romantic"] += 20
            traits["loves the cold"] -= 20
            traits["loves the heat"] += 20
            traits["loves the outdoors"] += 20
            traits["party animal"] += 20
            traits["perceptive"] -= 20
            traits["rebellious"] += 20
            traits["schmoozer"] += 20
            traits["shy"] -= 20
            traits["social butterfly"] += 20
            traits["socially awkward"] -= 20
            traits["star quality"] += 20
            traits["supernatural fan"] -= 20
            traits["supernatural sceptic"] += 20
            traits["technophobe"] += 20
            traits["unflirty"] -= 20
            traits["unstable"] += 20
            traits["virtuoso"] += 20
            traits["workaholic"] += 20
        case "Introvert":
            traits["adventurous"] += 20
            traits["ambitious"] += 20
            traits["bookworm"] -= 20
            traits["born salesman"] += 20
            traits["bot fan"] -= 20
            traits["brave"] -= 20
            traits["brooding"] -= 20
            traits["cat person"] -= 20
            traits["charismatic"] += 20
            traits["commitment issues"] += 20
            traits["coward"] -= 20
            traits["diva"] += 20
            traits["dog person"] += 20
            traits["dramatic"] += 20
            traits["easily impressed"] += 20
            traits["excitable"] += 20
            traits["flirty"] += 20
            traits["genius"] += 20
            traits["good sense of humour"] += 20
            traits["grumpy"] -= 20
            traits["hopeless romantic"] += 20
            traits["irresistible"] += 20
            traits["kleptomaniac"] += 20
            traits["loner"] -= 20
            traits["mooch"] += 20
            traits["natural born performer"] += 20
            traits["neurotic"] -= 20
            traits["never nude"] -= 20
            traits["night owl"] -= 20
            traits["no sense of humour"] -= 20
            traits["over-emotional"] += 20
            traits["party animal"] += 20
            traits["rebellious"] += 20
            traits["shy"] -= 20
            traits["social butterfly"] += 20
            traits["socially awkward"] -= 20
            traits["supernatural fan"] -= 20
            traits["supernatural sceptic"] += 20
            traits["unflirty"] -= 20
            traits["workaholic"] += 20
        case "Laid Back":
            traits["adventurous"] += 20
            traits["athletic"] += 20
            traits["born salesman"] += 20
            traits["brave"] += 20
            traits["cat person"] -= 20
            traits["charismatic"] += 20
            traits["computer whiz"] -= 20
            traits["couch potato"] -= 20
            traits["diva"] += 20
            traits["dog person"] += 20
            traits["dramatic"] += 20
            traits["equestrian"] += 20
            traits["excitable"] += 20
            traits["gatherer"] += 20
            traits["green thumb"] += 20
            traits["handy"] += 20
            traits["hates the outdoors"] -= 20
            traits["hydrophobic"] -= 20
            traits["loves the cold"] -= 20
            traits["loves the heat"] += 20
            traits["loves the outdoors"] += 20
            traits["loves to swim"] += 20
            traits["mooch"] -= 20
            traits["natural born performer"] += 20
            traits["natural cook"] += 20
            traits["proper"] += 20
            traits["rebellious"] += 20
            traits["sailor"] += 20
            traits["slob"] -= 20
            traits["social butterfly"] += 20
            traits["socially awkward"] -= 20
            traits["star quality"] += 20
            traits["technophobe"] += 20
            traits["vehicle enthusiast"] += 20
            traits["workaholic"] += 20
        case "Musical":
            traits["adventurous"] += 20
            traits["artistic"] += 20
            traits["avant garde"] += 20
            traits["bookworm"] += 20
            traits["bot fan"] += 20
            traits["brooding"] += 20
            traits["computer whiz"] += 20
            traits["couch potato"] += 20
            traits["diva"] -= 20
            traits["dramatic"] -= 20
            traits["eccentric"] += 20
            traits["evil"] += 20
            traits["genius"] += 20
            traits["irresistible"] -= 20
            traits["natural born performer"] -= 20
            traits["party animal"] -= 20
            traits["photographer's eye"] += 20
            traits["savvy sculptor"] += 20
            traits["star quality"] -= 20
            traits["virtuoso"] -= 20
            traits["workaholic"] += 20
        case "Occult":
            traits["absent-minded"] += 20
            traits["animal lover"] += 20
            traits["avant garde"] += 20
            traits["born salesman"] += 20
            traits["bot fan"] -= 20
            traits["brooding"] += 20
            traits["daredevil"] += 20
            traits["diva"] += 20
            traits["dramatic"] += 20
            traits["excitable"] += 20
            traits["grumpy"] += 20
            traits["hot-headed"] += 20
            traits["inappropriate"] -= 20
            traits["insane"] -= 20
            traits["irresistible"] += 20
            traits["loser"] -= 20
            traits["night owl"] -= 20
            traits["nurturing"] += 20
            traits["proper"] += 20
            traits["schmoozer"] += 20
            traits["supernatural fan"] -= 20
            traits["supernatural sceptic"] += 20
            traits["unlucky"] -= 20
            traits["unstable"] -= 20
            traits["workaholic"] += 20
        case "Outdoorsy":
            traits["absent-minded"] += 20
            traits["adventurous"] -= 20
            traits["angler"] -= 20
            traits["bookworm"] += 20
            traits["bot fan"] += 20
            traits["computer whiz"] += 20
            traits["couch potato"] += 20
            traits["eco-friendly"] -= 20
            traits["equestrian"] -= 20
            traits["gatherer"] -= 20
            traits["green thumb"] -= 20
            traits["hates the outdoors"] += 20
            traits["loves the cold"] += 20
            traits["loves the heat"] -= 20
            traits["loves the outdoors"] -= 20
            traits["loves to swim"] -= 20
            traits["sailor"] -= 20
            traits["shy"] += 20
            traits["technophobe"] -= 20
            traits["vehicle enthusiast"] -= 20
        case "Outgoing":
            traits["absent-minded"] += 20
            traits["ambitious"] -= 20
            traits["angler"] += 20
            traits["animal lover"] -= 20
            traits["bookworm"] += 20
            traits["born salesman"] -= 20
            traits["brave"] -= 20
            traits["brooding"] += 20
            traits["cat person"] += 20
            traits["charismatic"] -= 20
            traits["childish"] -= 20
            traits["clumsy"] += 20
            traits["commitment issues"] -= 20
            traits["coward"] += 20
            traits["diva"] -= 20
            traits["dog person"] -= 20
            traits["dramatic"] -= 20
            traits["excitable"] -= 20
            traits["flirty"] -= 20
            traits["genius"] += 20
            traits["good sense of humour"] -= 20
            traits["hopeless romantic"] -= 20
            traits["hot-headed"] += 20
            traits["inappropriate"] += 20
            traits["insane"] += 20
            traits["irresistible"] -= 20
            traits["loner"] += 20
            traits["loser"] += 20
            traits["mean-spirited"] += 20
            traits["natural born performer"] -= 20
            traits["neurotic"] += 20
            traits["no sense of humour"] += 20
            traits["over-emotional"] -= 20
            traits["party animal"] -= 20
            traits["proper"] += 20
            traits["rebellious"] -= 20
            traits["schmoozer"] -= 20
            traits["shy"] += 20
            traits["snob"] += 20
            traits["social butterfly"] -= 20
            traits["socially awkward"] += 20
            traits["star quality"] -= 20
            traits["unflirty"] += 20
            traits["unlucky"] += 20
            traits["unstable"] += 20
            traits["workaholic"] -= 20
        case "Plant Lover":
            traits["animal lover"] -= 20
            traits["bookworm"] += 20
            traits["bot fan"] += 20
            traits["cat person"] += 20
            traits["couch potato"] += 20
            traits["dog person"] -= 20
            traits["eco-friendly"] -= 20
            traits["gatherer"] -= 20
            traits["green thumb"] -= 20
            traits["hates the outdoors"] += 20
            traits["hydrophobic"] += 20
            traits["loves the cold"] += 20
            traits["loves the heat"] -= 20
            traits["loves the outdoors"] -= 20
            traits["loves to swim"] -= 20
            traits["supernatural fan"] -= 20
            traits["supernatural sceptic"] += 20
            traits["vegetarian"] -= 20
        case "Rebellious":
            traits["absent-minded"] += 20
            traits["ambitious"] += 20
            traits["animal lover"] += 20
            traits["bookworm"] += 20
            traits["bot fan"] += 20
            traits["brooding"] += 20
            traits["cat person"] += 20
            traits["clumsy"] += 20
            traits["coward"] += 20
            traits["daredevil"] -= 20
            traits["diva"] -= 20
            traits["dog person"] += 20
            traits["dramatic"] -= 20
            traits["easily impressed"] += 20
            traits["eco-friendly"] += 20
            traits["equestrian"] += 20
            traits["evil"] -= 20
            traits["excitable"] += 20
            traits["flirty"] += 20
            traits["friendly"] += 20
            traits["frugal"] += 20
            traits["good"] += 20
            traits["good sense of humour"] += 20
            traits["grumpy"] -= 20
            traits["hot-headed"] -= 20
            traits["inappropriate"] -= 20
            traits["insane"] -= 20
            traits["irresistible"] += 20
            traits["kleptomaniac"] -= 20
            traits["loner"] += 20
            traits["loser"] += 20
            traits["lucky"] += 20
            traits["natural born performer"] -= 20
            traits["neat"] += 20
            traits["proper"] += 20
            traits["rebellious"] -= 20
            traits["schmoozer"] -= 20
            traits["shy"] += 20
            traits["snob"] += 20
            traits["social butterfly"] += 20
            traits["socially awkward"] += 20
            traits["unflirty"] += 20
            traits["unlucky"] += 20
            traits["unstable"] -= 20
        case "Stylish":
            traits["absent-minded"] += 20
            traits["ambitious"] -= 20
            traits["angler"] += 20
            traits["bookworm"] += 20
            traits["bot fan"] += 20
            traits["charismatic"] -= 20
            traits["childish"] += 20
            traits["clumsy"] += 20
            traits["diva"] -= 20
            traits["dramatic"] -= 20
            traits["easily impressed"] += 20
            traits["eco-friendly"] += 20
            traits["evil"] -= 20
            traits["excitable"] += 20
            traits["family-oriented"] += 20
            traits["flirty"] -= 20
            traits["friendly"] += 20
            traits["frugal"] += 20
            traits["genius"] += 20
            traits["good"] += 20
            traits["hopeless romantic"] -= 20
            traits["irresistible"] -= 20
            traits["mooch"] += 20
            traits["natural born performer"] -= 20
            traits["over-emotional"] -= 20
            traits["party animal"] -= 20
            traits["perfectionist"] -= 20
            traits["photographer's eye"] -= 20
            traits["proper"] -= 20
            traits["schmoozer"] -= 20
            traits["shy"] += 20
            traits["snob"] -= 20
            traits["socially awkward"] += 20
            traits["star quality"] -= 20
            traits["unflirty"] += 20
            traits["unlucky"] += 20
            traits["workaholic"] += 20
        case "Technology":
            traits["ambitious"] += 20
            traits["artistic"] += 20
            traits["avant garde"] += 20
            traits["bookworm"] += 20
            traits["bot fan"] -= 20
            traits["brooding"] += 20
            traits["can't stand art"] -= 20
            traits["computer whiz"] -= 20
            traits["couch potato"] -= 20
            traits["green thumb"] += 20
            traits["grumpy"] += 20
            traits["handy"] -= 20
            traits["inappropriate"] += 20
            traits["insane"] += 20
            traits["natural cook"] -= 20
            traits["photographer's eye"] -= 20
            traits["savvy sculptor"] += 20
            traits["technophobe"] += 20
            traits["vehicle enthusiast"] -= 20
            traits["virtuoso"] -= 20
        case "Tidy":
            traits["absent-minded"] += 20
            traits["angler"] += 20
            traits["animal lover"] += 20
            traits["cat person"] += 20
            traits["childish"] += 20
            traits["clumsy"] += 20
            traits["commitment issues"] += 20
            traits["dislikes children"] += 20
            traits["diva"] += 20
            traits["dog person"] -= 20
            traits["dramatic"] += 20
            traits["family-oriented"] -= 20
            traits["friendly"] -= 20
            traits["frugal"] -= 20
            traits["gatherer"] += 20
            traits["genius"] -= 20
            traits["green thumb"] += 20
            traits["grumpy"] += 20
            traits["heavy sleeper"] -= 20
            traits["hopeless romantic"] += 20
            traits["irresistible"] += 20
            traits["kleptomaniac"] += 20
            traits["light sleeper"] += 20
            traits["lucky"] -= 20
            traits["mean-spirited"] += 20
            traits["mooch"] += 20
            traits["neat"] -= 20
            traits["never nude"] -= 20
            traits["night owl"] -= 20
            traits["nurturing"] -= 20
            traits["perfectionist"] -= 20
            traits["photographer's eye"] -= 20
            traits["proper"] -= 20
            traits["unlucky"] += 20
        case "Undead":
            traits["adventurous"] += 20
            traits["ambitious"] += 20
            traits["animal lover"] += 20
            traits["born salesman"] += 20
            traits["brave"] += 20
            traits["charismatic"] += 20
            traits["clumsy"] += 20
            traits["commitment issues"] += 20
            traits["coward"] += 20
            traits["disciplined"] += 20
            traits["diva"] += 20
            traits["dramatic"] += 20
            traits["easily impressed"] += 20
            traits["excitable"] += 20
            traits["flirty"] += 20
            traits["good sense of humour"] += 20
            traits["grumpy"] -= 20
            traits["hopeless romantic"] += 20
            traits["inappropriate"] -= 20
            traits["insane"] -= 20
            traits["irresistible"] += 20
            traits["kleptomaniac"] -= 20
            traits["loner"] -= 20
            traits["loser"] -= 20
            traits["lucky"] += 20
            traits["night owl"] -= 20
            traits["no sense of humour"] -= 20
            traits["over-emotional"] += 20
            traits["party animal"] += 20
            traits["social butterfly"] += 20
            traits["socially awkward"] -= 20
            traits["supernatural fan"] -= 20
            traits["supernatural sceptic"] += 20
            traits["unflirty"] -= 20
            traits["unlucky"] -= 20
        case "Well-Liked":
            traits["absent-minded"] -= 20
            traits["ambitious"] += 20
            traits["animal lover"] -= 20
            traits["brooding"] += 20
            traits["cat person"] -= 20
            traits["charismatic"] += 20
            traits["childish"] += 20
            traits["commitment issues"] += 20
            traits["daredevil"] += 20
            traits["dislikes children"] += 20
            traits["diva"] += 20
            traits["dog person"] -= 20
            traits["dramatic"] += 20
            traits["easily impressed"] -= 20
            traits["evil"] += 20
            traits["excitable"] -= 20
            traits["family-oriented"] -= 20
            traits["friendly"] -= 20
            traits["good"] -= 20
            traits["good sense of humour"] -= 20
            traits["grumpy"] += 20
            traits["hopeless romantic"] -= 20
            traits["inappropriate"] += 20
            traits["insane"] += 20
            traits["irresistible"] += 20
            traits["kleptomaniac"] += 20
            traits["lucky"] += 20
            traits["mean-spirited"] += 20
            traits["mooch"] += 20
            traits["never nude"] -= 20
            traits["no sense of humour"] += 20
            traits["nurturing"] -= 20
            traits["proper"] -= 20
            traits["rebellious"] += 20
            traits["supernatural fan"] -= 20
            traits["supernatural sceptic"] += 20
            traits["unflirty"] -= 20
            traits["unlucky"] -= 20


def get_trait_turn_on(turn_on, traits):
    # Turn On
    match (turn_on):
        case "Adventurous":
            traits["absent-minded"] -= 20
            traits["adventurous"] += 20
            traits["ambitious"] += 20
            traits["athletic"] += 20
            traits["born salesman"] += 20
            traits["brave"] += 20
            traits["brooding"] -= 20
            traits["charismatic"] += 20
            traits["clumsy"] -= 20
            traits["commitment issues"] -= 20
            traits["couch potato"] -= 20
            traits["coward"] -= 20
            traits["daredevil"] += 20
            traits["diva"] -= 20
            traits["dramatic"] -= 20
            traits["easily impressed"] -= 20
            traits["evil"] += 20
            traits["excitable"] += 20
            traits["flirty"] -= 20
            traits["friendly"] -= 20
            traits["gatherer"] += 20
            traits["grumpy"] -= 20
            traits["hates the outdoors"] -= 20
            traits["heavy sleeper"] -= 20
            traits["hydrophobic"] -= 20
            traits["inappropriate"] -= 20
            traits["insane"] -= 20
            traits["irresistible"] -= 20
            traits["kleptomaniac"] += 20
            traits["light sleeper"] += 20
            traits["loner"] -= 20
            traits["loser"] -= 20
            traits["loves the cold"] -= 20
            traits["loves the heat"] += 20
            traits["loves the outdoors"] += 20
            traits["lucky"] += 20
            traits["neurotic"] -= 20
            traits["never nude"] -= 20
            traits["shy"] -= 20
            traits["social butterfly"] += 20
            traits["socially awkward"] -= 20
            traits["supernatural fan"] += 20
            traits["supernatural sceptic"] -= 20
            traits["unlucky"] -= 20
            traits["unstable"] -= 20
        case "Alien":
            traits["absent-minded"] -= 20
            traits["adventurous"] += 20
            traits["bookworm"] += 20
            traits["bot fan"] += 20
            traits["brave"] += 20
            traits["brooding"] -= 20
            traits["commitment issues"] -= 20
            traits["coward"] += 20
            traits["diva"] -= 20
            traits["dramatic"] -= 20
            traits["evil"] -= 20
            traits["flirty"] -= 20
            traits["grumpy"] -= 20
            traits["inappropriate"] -= 20
            traits["insane"] -= 20
            traits["irresistible"] -= 20
            traits["night owl"] += 20
            traits["proper"] -= 20
            traits["rebellious"] -= 20
            traits["shy"] += 20
            traits["social butterfly"] -= 20
            traits["socially awkward"] += 20
            traits["supernatural fan"] += 20
            traits["supernatural sceptic"] -= 20
        case "Animal Lover":
            traits["animal lover"] += 20
            traits["cat person"] += 20
            traits["dog person"] += 20
            traits["equestrian"] += 20
            traits["evil"] -= 20
            traits["family-oriented"] += 20
            traits["grumpy"] -= 20
            traits["inappropriate"] -= 20
            traits["insane"] -= 20
            traits["kleptomaniac"] -= 20
            traits["neat"] -= 20
            traits["socially awkward"] -= 20
        case "Artistic":
            traits["absent-minded"] -= 20
            traits["ambitious"] += 20
            traits["artistic"] += 20
            traits["avant garde"] += 20
            traits["brooding"] -= 20
            traits["can't stand art"] -= 20
            traits["eccentric"] -= 20
            traits["evil"] -= 20
            traits["photographer's eye"] += 20
            traits["savvy sculptor"] += 20
            traits["star quality"] += 20
            traits["virtuoso"] += 20
        case "Athletic":
            traits["ambitious"] += 20
            traits["athletic"] += 20
            traits["daredevil"] += 20
            traits["disciplined"] += 20
            traits["equestrian"] += 20
            traits["hydrophobic"] -= 20
            traits["loves to swim"] += 20
            traits["sailor"] += 20
        case "Business Shark":
            traits["absent-minded"] -= 20
            traits["ambitious"] += 20
            traits["born salesman"] += 20
            traits["easily impressed"] -= 20
            traits["excitable"] -= 20
            traits["family-oriented"] -= 20
            traits["friendly"] -= 20
            traits["good"] -= 20
            traits["good sense of humour"] -= 20
            traits["grumpy"] += 20
            traits["heavy sleeper"] -= 20
            traits["light sleeper"] += 20
            traits["mean-spirited"] += 20
            traits["nurturing"] -= 20
            traits["schmoozer"] += 20
            traits["shy"] -= 20
            traits["snob"] += 20
            traits["star quality"] += 20
            traits["workaholic"] += 20
        case "Charismatic":
            traits["brooding"] -= 20
            traits["charismatic"] += 20
            traits["diva"] += 20
            traits["dramatic"] += 20
            traits["excitable"] += 20
            traits["flirty"] += 20
            traits["friendly"] += 20
            traits["good"] += 20
            traits["good sense of humour"] += 20
            traits["grumpy"] -= 20
            traits["hopeless romantic"] += 20
            traits["hot-headed"] -= 20
            traits["inappropriate"] -= 20
            traits["insane"] -= 20
            traits["irresistible"] += 20
            traits["light sleeper"] += 20
            traits["loner"] -= 20
            traits["loser"] -= 20
            traits["mean-spirited"] -= 20
            traits["natural born performer"] += 20
            traits["no sense of humour"] -= 20
            traits["rebellious"] -= 20
            traits["schmoozer"] += 20
            traits["shy"] -= 20
            traits["social butterfly"] += 20
            traits["socially awkward"] -= 20
            traits["star quality"] += 20
        case "Cultured":
            traits["absent-minded"] -= 20
            traits["artistic"] += 20
            traits["avant garde"] += 20
            traits["bookworm"] += 20
            traits["born salesman"] -= 20
            traits["bot fan"] -= 20
            traits["can't stand art"] -= 20
            traits["couch potato"] += 20
            traits["diva"] += 20
            traits["loves the cold"] += 20
            traits["loves the heat"] -= 20
            traits["photographer's eye"] += 20
            traits["savvy sculptor"] += 20
            traits["snob"] -= 20
            traits["technophobe"] -= 20
            traits["virtuoso"] += 20
        case "Expressive":
            traits["adventurous"] += 20
            traits["artistic"] += 20
            traits["avant garde"] += 20
            traits["bookworm"] -= 20
            traits["brooding"] -= 20
            traits["charismatic"] += 20
            traits["childish"] += 20
            traits["diva"] += 20
            traits["dramatic"] += 20
            traits["excitable"] += 20
            traits["grumpy"] -= 20
            traits["loner"] -= 20
            traits["loser"] -= 20
            traits["mean-spirited"] -= 20
            traits["neurotic"] -= 20
            traits["no sense of humour"] -= 20
            traits["over-emotional"] += 20
            traits["party animal"] += 20
            traits["rebellious"] -= 20
            traits["shy"] -= 20
            traits["social butterfly"] += 20
            traits["socially awkward"] -= 20
        case "Fatness":
            traits["adventurous"] -= 20
            traits["couch potato"] += 20
            traits["disciplined"] -= 20
            traits["equestrian"] -= 20
            traits["hates the outdoors"] += 20
            traits["heavy sleeper"] += 20
            traits["light sleeper"] -= 20
            traits["loves the cold"] += 20
            traits["loves the heat"] -= 20
            traits["loves the outdoors"] -= 20
            traits["loves to swim"] -= 20
            traits["never nude"] += 20
            traits["sailor"] -= 20
            traits["slob"] += 20
            traits["vegetarian"] -= 20
        case "Fitness":
            traits["couch potato"] -= 20
            traits["disciplined"] += 20
            traits["hates the outdoors"] -= 20
            traits["heavy sleeper"] -= 20
            traits["hydrophobic"] -= 20
            traits["light sleeper"] += 20
            traits["loves the cold"] -= 20
            traits["loves the heat"] += 20
            traits["loves the outdoors"] += 20
            traits["loves to swim"] += 20
            traits["sailor"] += 20
            traits["vegetarian"] += 20
        case "Foodie":
            traits["artistic"] += 20
            traits["can't stand art"] -= 20
            traits["clumsy"] -= 20
            traits["evil"] -= 20
            traits["family-oriented"] += 20
            traits["grumpy"] -= 20
            traits["hot-headed"] -= 20
            traits["irresistible"] -= 20
            traits["mean-spirited"] -= 20
            traits["natural cook"] += 20
            traits["neat"] += 20
            traits["nurturing"] += 20
            traits["rebellious"] -= 20
            traits["slob"] -= 20
            traits["snob"] += 20
            traits["vegetarian"] += 20
        case "Indoorsy":
            traits["adventurous"] -= 20
            traits["angler"] -= 20
            traits["bookworm"] += 20
            traits["bot fan"] += 20
            traits["computer whiz"] += 20
            traits["couch potato"] += 20
            traits["eco-friendly"] -= 20
            traits["equestrian"] -= 20
            traits["gatherer"] -= 20
            traits["green thumb"] -= 20
            traits["hates the outdoors"] += 20
            traits["loves the cold"] += 20
            traits["loves the heat"] -= 20
            traits["loves the outdoors"] -= 20
            traits["night owl"] += 20
            traits["sailor"] -= 20
            traits["shy"] += 20
            traits["technophobe"] -= 20
            traits["vehicle enthusiast"] -= 20
        case "Infamous":
            traits["animal lover"] -= 20
            traits["avant garde"] += 20
            traits["charismatic"] -= 20
            traits["childish"] -= 20
            traits["commitment issues"] += 20
            traits["coward"] -= 20
            traits["daredevil"] += 20
            traits["disciplined"] -= 20
            traits["dislikes children"] += 20
            traits["diva"] += 20
            traits["dramatic"] += 20
            traits["easily impressed"] -= 20
            traits["evil"] += 20
            traits["excitable"] += 20
            traits["family-oriented"] -= 20
            traits["friendly"] -= 20
            traits["good"] -= 20
            traits["good sense of humour"]
            traits["hopeless romantic"] -= 20
            traits["inappropriate"] += 20
            traits["insane"] += 20
            traits["lucky"] -= 20
            traits["mean-spirited"] += 20
            traits["natural cook"] -= 20
            traits["neat"] -= 20
            traits["nurturing"] -= 20
            traits["over-emotional"] -= 20
            traits["perceptive"] -= 20
            traits["perfectionist"] -= 20
            traits["proper"] -= 20
            traits["rebellious"] += 20
            traits["shy"] -= 20
            traits["supernatural fan"] -= 20
            traits["supernatural sceptic"] += 20
            traits["unlucky"] += 20
            traits["unstable"] += 20
        case "Intellect":
            traits["absent-minded"] -= 20
            traits["ambitious"] -= 20
            traits["artistic"] -= 20
            traits["bookworm"] += 20
            traits["brooding"] += 20
            traits["childish"] -= 20
            traits["commitment issues"] -= 20
            traits["evil"] -= 20
            traits["excitable"] -= 20
            traits["genius"] += 20
            traits["grumpy"] += 20
            traits["hates the outdoors"] += 20
            traits["hopeless romantic"] -= 20
            traits["loves the cold"] += 20
            traits["loves the heat"] -= 20
            traits["loves the outdoors"] -= 20
            traits["party animal"] -= 20
            traits["perceptive"] += 20
            traits["rebellious"] -= 20
            traits["schmoozer"] -= 20
            traits["shy"] += 20
            traits["social butterfly"] -= 20
            traits["socially awkward"] += 20
            traits["star quality"] -= 20
            traits["supernatural fan"] += 20
            traits["supernatural sceptic"] -= 20
            traits["technophobe"] -= 20
            traits["unflirty"] += 20
            traits["unstable"] -= 20
            traits["virtuoso"] -= 20
            traits["workaholic"] -= 20
        case "Introvert":
            traits["adventurous"] -= 20
            traits["ambitious"] -= 20
            traits["bookworm"] += 20
            traits["born salesman"] -= 20
            traits["bot fan"] += 20
            traits["brave"] += 20
            traits["brooding"] += 20
            traits["cat person"] += 20
            traits["charismatic"] -= 20
            traits["commitment issues"] -= 20
            traits["coward"] += 20
            traits["diva"] -= 20
            traits["dog person"] -= 20
            traits["dramatic"] -= 20
            traits["easily impressed"] -= 20
            traits["excitable"] -= 20
            traits["flirty"] -= 20
            traits["genius"] -= 20
            traits["good sense of humour"] -= 20
            traits["grumpy"] += 20
            traits["hopeless romantic"] -= 20
            traits["irresistible"] -= 20
            traits["kleptomaniac"] -= 20
            traits["loner"] += 20
            traits["mooch"] -= 20
            traits["natural born performer"] -= 20
            traits["neurotic"] += 20
            traits["never nude"] += 20
            traits["night owl"] += 20
            traits["no sense of humour"] += 20
            traits["over-emotional"] -= 20
            traits["party animal"] -= 20
            traits["rebellious"] -= 20
            traits["shy"] += 20
            traits["social butterfly"] -= 20
            traits["socially awkward"] += 20
            traits["supernatural fan"] += 20
            traits["supernatural sceptic"] -= 20
            traits["unflirty"] += 20
            traits["workaholic"] -= 20
        case "Laid Back":
            traits["adventurous"] -= 20
            traits["athletic"] -= 20
            traits["born salesman"] -= 20
            traits["brave"] -= 20
            traits["cat person"] += 20
            traits["charismatic"] -= 20
            traits["computer whiz"] += 20
            traits["couch potato"] += 20
            traits["diva"] -= 20
            traits["dog person"] -= 20
            traits["dramatic"] -= 20
            traits["equestrian"] -= 20
            traits["excitable"] -= 20
            traits["gatherer"] -= 20
            traits["green thumb"] -= 20
            traits["handy"] -= 20
            traits["hates the outdoors"] += 20
            traits["hydrophobic"] += 20
            traits["loves the cold"] += 20
            traits["loves the heat"] -= 20
            traits["loves the outdoors"] -= 20
            traits["loves to swim"] -= 20
            traits["mooch"] += 20
            traits["natural born performer"] -= 20
            traits["natural cook"] -= 20
            traits["proper"] -= 20
            traits["rebellious"] -= 20
            traits["sailor"] -= 20
            traits["slob"] += 20
            traits["social butterfly"] -= 20
            traits["socially awkward"] += 20
            traits["star quality"] -= 20
            traits["technophobe"] -= 20
            traits["vehicle enthusiast"] -= 20
            traits["workaholic"] -= 20
        case "Musical":
            traits["adventurous"] -= 20
            traits["artistic"] -= 20
            traits["avant garde"] -= 20
            traits["bookworm"] -= 20
            traits["bot fan"] -= 20
            traits["brooding"] -= 20
            traits["computer whiz"] -= 20
            traits["couch potato"] -= 20
            traits["diva"] += 20
            traits["dramatic"] += 20
            traits["eccentric"] -= 20
            traits["evil"] -= 20
            traits["genius"] -= 20
            traits["irresistible"] += 20
            traits["natural born performer"] += 20
            traits["party animal"] += 20
            traits["photographer's eye"] -= 20
            traits["savvy sculptor"] -= 20
            traits["star quality"] += 20
            traits["virtuoso"] += 20
            traits["workaholic"] -= 20
        case "Occult":
            traits["absent-minded"] -= 20
            traits["animal lover"] -= 20
            traits["avant garde"] -= 20
            traits["born salesman"] -= 20
            traits["bot fan"] += 20
            traits["brooding"] -= 20
            traits["daredevil"] -= 20
            traits["diva"] -= 20
            traits["dramatic"] -= 20
            traits["excitable"] -= 20
            traits["grumpy"] -= 20
            traits["hot-headed"] -= 20
            traits["inappropriate"] += 20
            traits["insane"] += 20
            traits["irresistible"] -= 20
            traits["loser"] += 20
            traits["night owl"] += 20
            traits["nurturing"] -= 20
            traits["proper"] -= 20
            traits["schmoozer"] -= 20
            traits["supernatural fan"] += 20
            traits["supernatural sceptic"] -= 20
            traits["unlucky"] += 20
            traits["unstable"] += 20
            traits["workaholic"] -= 20
        case "Outdoorsy":
            traits["absent-minded"] -= 20
            traits["adventurous"] += 20
            traits["angler"] += 20
            traits["bookworm"] -= 20
            traits["bot fan"] -= 20
            traits["computer whiz"] -= 20
            traits["couch potato"] -= 20
            traits["eco-friendly"] += 20
            traits["equestrian"] += 20
            traits["gatherer"] += 20
            traits["green thumb"] += 20
            traits["hates the outdoors"] -= 20
            traits["loves the cold"] -= 20
            traits["loves the heat"] += 20
            traits["loves the outdoors"] += 20
            traits["loves to swim"] += 20
            traits["sailor"] += 20
            traits["shy"] -= 20
            traits["technophobe"] += 20
            traits["vehicle enthusiast"] += 20
        case "Outgoing":
            traits["absent-minded"] -= 20
            traits["ambitious"] += 20
            traits["angler"] -= 20
            traits["animal lover"] += 20
            traits["bookworm"] -= 20
            traits["born salesman"] += 20
            traits["brave"] += 20
            traits["brooding"] -= 20
            traits["cat person"] -= 20
            traits["charismatic"] += 20
            traits["childish"] += 20
            traits["clumsy"] -= 20
            traits["commitment issues"] += 20
            traits["coward"] -= 20
            traits["diva"] += 20
            traits["dog person"] += 20
            traits["dramatic"] += 20
            traits["excitable"] += 20
            traits["flirty"] += 20
            traits["genius"] -= 20
            traits["good sense of humour"] += 20
            traits["hopeless romantic"] += 20
            traits["hot-headed"] -= 20
            traits["inappropriate"] -= 20
            traits["insane"] -= 20
            traits["irresistible"] += 20
            traits["loner"] -= 20
            traits["loser"] -= 20
            traits["mean-spirited"] -= 20
            traits["natural born performer"] += 20
            traits["neurotic"] -= 20
            traits["no sense of humour"] -= 20
            traits["over-emotional"] += 20
            traits["party animal"] += 20
            traits["proper"] -= 20
            traits["rebellious"] += 20
            traits["schmoozer"] += 20
            traits["shy"] -= 20
            traits["snob"] -= 20
            traits["social butterfly"] += 20
            traits["socially awkward"] -= 20
            traits["star quality"] += 20
            traits["unflirty"] -= 20
            traits["unlucky"] -= 20
            traits["unstable"] -= 20
            traits["workaholic"] -= 20
        case "Plant Lover":
            traits["animal lover"] += 20
            traits["bookworm"] -= 20
            traits["bot fan"] -= 20
            traits["cat person"] -= 20
            traits["couch potato"] -= 20
            traits["dog person"] += 20
            traits["eco-friendly"] += 20
            traits["gatherer"] += 20
            traits["green thumb"] += 20
            traits["hates the outdoors"] -= 20
            traits["hydrophobic"] -= 20
            traits["loves the cold"] -= 20
            traits["loves the heat"] += 20
            traits["loves the outdoors"] += 20
            traits["loves to swim"] += 20
            traits["supernatural fan"] += 20
            traits["supernatural sceptic"] -= 20
            traits["vegetarian"] += 20
        case "Rebellious":
            traits["absent-minded"] -= 20
            traits["ambitious"] -= 20
            traits["animal lover"] -= 20
            traits["bookworm"] -= 20
            traits["bot fan"] -= 20
            traits["brooding"] -= 20
            traits["cat person"] -= 20
            traits["clumsy"] -= 20
            traits["coward"] -= 20
            traits["daredevil"] += 20
            traits["diva"] += 20
            traits["dog person"] -= 20
            traits["dramatic"] += 20
            traits["easily impressed"] -= 20
            traits["eco-friendly"] -= 20
            traits["equestrian"] -= 20
            traits["evil"] += 20
            traits["excitable"] -= 20
            traits["flirty"] -= 20
            traits["friendly"] -= 20
            traits["frugal"] -= 20
            traits["good"] -= 20
            traits["good sense of humour"] -= 20
            traits["grumpy"] += 20
            traits["hot-headed"] += 20
            traits["inappropriate"] += 20
            traits["insane"] += 20
            traits["irresistible"] -= 20
            traits["kleptomaniac"] += 20
            traits["loner"] -= 20
            traits["loser"] -= 20
            traits["lucky"] -= 20
            traits["natural born performer"] += 20
            traits["neat"] -= 20
            traits["proper"] -= 20
            traits["rebellious"] += 20
            traits["schmoozer"] += 20
            traits["shy"] -= 20
            traits["snob"] -= 20
            traits["social butterfly"] -= 20
            traits["socially awkward"] -= 20
            traits["unflirty"] -= 20
            traits["unlucky"] -= 20
            traits["unstable"] -= 20
        case "Stylish":
            traits["absent-minded"] -= 20
            traits["ambitious"] += 20
            traits["angler"] -= 20
            traits["bookworm"] -= 20
            traits["bot fan"] -= 20
            traits["charismatic"] += 20
            traits["childish"] -= 20
            traits["clumsy"] -= 20
            traits["diva"] += 20
            traits["dramatic"] += 20
            traits["easily impressed"] -= 20
            traits["eco-friendly"] -= 20
            traits["evil"] += 20
            traits["excitable"] -= 20
            traits["family-oriented"] -= 20
            traits["flirty"] += 20
            traits["friendly"] -= 20
            traits["frugal"] -= 20
            traits["genius"] -= 20
            traits["good"] -= 20
            traits["hopeless romantic"] += 20
            traits["irresistible"] += 20
            traits["mooch"] -= 20
            traits["natural born performer"] += 20
            traits["over-emotional"] += 20
            traits["party animal"] += 20
            traits["perfectionist"] += 20
            traits["photographer's eye"] += 20
            traits["proper"] += 20
            traits["schmoozer"] += 20
            traits["shy"] -= 20
            traits["snob"] += 20
            traits["socially awkward"] -= 20
            traits["star quality"] += 20
            traits["unflirty"] -= 20
            traits["unlucky"] -= 20
            traits["workaholic"] -= 20
        case "Technology":
            traits["ambitious"] -= 20
            traits["artistic"] -= 20
            traits["avant garde"] -= 20
            traits["bookworm"] -= 20
            traits["bot fan"] += 20
            traits["brooding"] -= 20
            traits["can't stand art"] += 20
            traits["computer whiz"] += 20
            traits["couch potato"] += 20
            traits["green thumb"] -= 20
            traits["grumpy"] -= 20
            traits["handy"] += 20
            traits["inappropriate"] -= 20
            traits["insane"] -= 20
            traits["natural cook"] += 20
            traits["photographer's eye"] += 20
            traits["savvy sculptor"] -= 20
            traits["technophobe"] -= 20
            traits["vehicle enthusiast"] += 20
            traits["virtuoso"] += 20
        case "Tidy":
            traits["absent-minded"] -= 11
            traits["angler"] -= 20
            traits["animal lover"] -= 20
            traits["cat person"] -= 20
            traits["charismatic"]
            traits["childish"] -= 20
            traits["clumsy"] -= 20
            traits["commitment issues"] -= 20
            traits["dislikes children"] -= 20
            traits["diva"] -= 20
            traits["dog person"] -= 20
            traits["dramatic"] -= 20
            traits["family-oriented"] += 20
            traits["friendly"] += 20
            traits["frugal"] += 20
            traits["gatherer"] -= 20
            traits["genius"] += 20
            traits["green thumb"] -= 20
            traits["grumpy"] -= 20
            traits["heavy sleeper"] += 20
            traits["hopeless romantic"] -= 20
            traits["irresistible"] -= 20
            traits["kleptomaniac"] -= 20
            traits["light sleeper"] -= 20
            traits["lucky"] += 20
            traits["mean-spirited"] -= 20
            traits["mooch"] -= 20
            traits["neat"] += 20
            traits["never nude"] += 20
            traits["night owl"] += 20
            traits["nurturing"] += 20
            traits["perfectionist"] += 20
            traits["photographer's eye"] += 20
            traits["proper"] += 20
            traits["unlucky"] -= 20
        case "Undead":
            traits["adventurous"] -= 20
            traits["ambitious"] -= 20
            traits["animal lover"] -= 20
            traits["born salesman"] -= 20
            traits["brave"] -= 20
            traits["charismatic"] -= 20
            traits["clumsy"] -= 20
            traits["commitment issues"] -= 20
            traits["coward"] -= 20
            traits["disciplined"] -= 20
            traits["diva"] -= 20
            traits["dramatic"] -= 20
            traits["easily impressed"] -= 20
            traits["excitable"] -= 20
            traits["flirty"] -= 20
            traits["good sense of humour"] -= 20
            traits["grumpy"] += 20
            traits["hopeless romantic"] -= 20
            traits["inappropriate"] += 20
            traits["insane"] += 20
            traits["irresistible"] -= 20
            traits["kleptomaniac"] += 20
            traits["loner"] += 20
            traits["loser"] += 20
            traits["lucky"] -= 20
            traits["night owl"] += 20
            traits["no sense of humour"] += 20
            traits["over-emotional"] -= 20
            traits["party animal"] -= 20
            traits["social butterfly"] -= 20
            traits["socially awkward"] += 20
            traits["supernatural fan"] += 20
            traits["supernatural sceptic"] -= 20
            traits["unflirty"] += 20
            traits["unlucky"] += 20
        case "Well-Liked":
            traits["absent-minded"] += 20
            traits["ambitious"] -= 20
            traits["animal lover"] += 20
            traits["brooding"] -= 20
            traits["cat person"] += 20
            traits["charismatic"] -= 20
            traits["childish"] -= 20
            traits["commitment issues"] -= 20
            traits["daredevil"] -= 20
            traits["dislikes children"] -= 20
            traits["diva"] -= 20
            traits["dog person"] += 20
            traits["dramatic"] -= 20
            traits["easily impressed"] += 20
            traits["evil"] -= 20
            traits["excitable"] += 20
            traits["family-oriented"] += 20
            traits["friendly"] += 20
            traits["good"] += 20
            traits["good sense of humour"] += 20
            traits["grumpy"] -= 20
            traits["hopeless romantic"] += 20
            traits["inappropriate"] -= 20
            traits["insane"] -= 20
            traits["irresistible"] -= 20
            traits["kleptomaniac"] -= 20
            traits["lucky"] -= 20
            traits["mean-spirited"] -= 20
            traits["mooch"] -= 20
            traits["never nude"] += 20
            traits["no sense of humour"] -= 20
            traits["nurturing"] += 20
            traits["proper"] += 20
            traits["rebellious"] -= 20
            traits["supernatural fan"] += 20
            traits["supernatural sceptic"] -= 20
            traits["unflirty"] += 20
            traits["unlucky"] += 20
